:- module(table,[get_tables/4,
                 get_table/4 ]).

get_tables(MaxN, NParam, BoundOrOptions, TableNames) :-
    findall(Name-MaxN, table(Name,MaxN,_,NParam,BoundOrOptions), TableNames).

get_table(MaxN, NParam, BoundOrOptions, TableName) :-
    table(TableName, MaxN, _, NParam, BoundOrOptions), !. % in principle table name should be distinct, but who knows

% Each table has the following five arguments:
%  . the name of the table
%  . the value of MaxN (i.e. the maximum number of vertices) used to generate the table
%  . the number of columns of the table
%  . the number of parameters of the lower/upper bound
%  . the lower/upper bound considered

:- dynamic table/5.


table(low_v_maxp,2,6,1,low(maxp)).
table(low_v_maxd,2,6,1,low(maxd)).
table(low_v_minp,2,6,1,low(minp)).
table(up_v_maxp,2,6,1,up(maxp)).
table(up_v_minp,2,6,1,up(minp)).
table(up_v_maxd,2,6,1,up(maxd)).
table(low_v_f,2,6,1,low(f)).
table(low_v_mind,2,6,1,low(mind)).
table(up_v_f,2,6,1,up(f)).
table(up_v_mind,2,6,1,up(mind)).
table(low_v_maxp_f,2,6,2,low(f)).
table(up_v_maxp_f,2,6,2,up(f)).
table(low_v_maxp_maxd,2,6,2,low(maxd)).
table(up_v_maxp_maxd,2,6,2,up(maxd)).
table(low_v_maxp_mind,2,6,2,low(mind)).
table(low_v_maxp_minp,2,6,2,low(minp)).
table(up_v_maxp_mind,2,6,2,up(mind)).
table(up_v_maxp_minp,2,6,2,up(minp)).
table(low_v_minp_maxp,2,6,2,low(maxp)).
table(up_v_minp_maxp,2,6,2,up(maxp)).
table(low_v_minp_f,2,6,2,low(f)).
table(up_v_minp_f,2,6,2,up(f)).
table(low_v_minp_mind,2,6,2,low(mind)).
table(up_v_minp_mind,2,6,2,up(mind)).
table(low_v_minp_maxd,2,6,2,low(maxd)).
table(up_v_minp_maxd,2,6,2,up(maxd)).
table(low_v_maxd_minp,2,6,2,low(minp)).
table(up_v_maxd_minp,2,6,2,up(minp)).
table(low_v_maxd_maxp,2,6,2,low(maxp)).
table(up_v_maxd_maxp,2,6,2,up(maxp)).
table(low_v_maxd_f,2,6,2,low(f)).
table(up_v_maxd_f,2,6,2,up(f)).
table(low_v_maxd_mind,2,6,2,low(mind)).
table(up_v_maxd_mind,2,6,2,up(mind)).
table(low_v_mind_maxd,2,6,2,low(maxd)).
table(up_v_mind_maxd,2,6,2,up(maxd)).
table(low_v_mind_minp,2,6,2,low(minp)).
table(up_v_mind_minp,2,6,2,up(minp)).
table(low_v_mind_maxp,2,6,2,low(maxp)).
table(up_v_mind_maxp,2,6,2,up(maxp)).
table(low_v_mind_f,2,6,2,low(f)).
table(up_v_mind_f,2,6,2,up(f)).
table(low_v_f_mind,2,6,2,low(mind)).
table(up_v_f_mind,2,6,2,up(mind)).
table(low_v_f_maxd,2,6,2,low(maxd)).
table(up_v_f_maxd,2,6,2,up(maxd)).
table(low_v_f_minp,2,6,2,low(minp)).
table(up_v_f_minp,2,6,2,up(minp)).
table(low_v_f_maxp,2,6,2,low(maxp)).
table(low_v_minp_maxp_f,2,6,3,low(f)).
table(up_v_f_maxp,2,6,2,up(maxp)).
table(up_v_minp_maxp_f,2,6,3,up(f)).
table(low_v_minp_maxp_mind,2,6,3,low(mind)).
table(up_v_minp_maxp_mind,2,6,3,up(mind)).
table(low_v_minp_maxp_maxd,2,6,3,low(maxd)).
table(low_v_maxd_minp_maxp,2,6,3,low(maxp)).
table(up_v_minp_maxp_maxd,2,6,3,up(maxd)).
table(up_v_maxd_minp_maxp,2,6,3,up(maxp)).
table(low_v_maxd_minp_f,2,6,3,low(f)).
table(up_v_maxd_minp_f,2,6,3,up(f)).
table(low_v_maxd_minp_mind,2,6,3,low(mind)).
table(up_v_maxd_minp_mind,2,6,3,up(mind)).
table(low_v_maxd_maxp_minp,2,6,3,low(minp)).
table(up_v_maxd_maxp_minp,2,6,3,up(minp)).
table(low_v_maxd_maxp_f,2,6,3,low(f)).
table(up_v_maxd_maxp_f,2,6,3,up(f)).
table(low_v_maxd_maxp_mind,2,6,3,low(mind)).
table(up_v_maxd_maxp_mind,2,6,3,up(mind)).
table(low_v_mind_maxd_maxp,2,6,3,low(maxp)).
table(up_v_mind_maxd_maxp,2,6,3,up(maxp)).
table(low_v_mind_maxd_minp,2,6,3,low(minp)).
table(up_v_mind_maxd_minp,2,6,3,up(minp)).
table(low_v_mind_maxd_f,2,6,3,low(f)).
table(low_v_mind_minp_maxd,2,6,3,low(maxd)).
table(up_v_mind_maxd_f,2,6,3,up(f)).
table(low_v_mind_minp_maxp,2,6,3,low(maxp)).
table(up_v_mind_minp_maxd,2,6,3,up(maxd)).
table(up_v_mind_minp_maxp,2,6,3,up(maxp)).
table(low_v_mind_minp_f,2,6,3,low(f)).
table(up_v_mind_minp_f,2,6,3,up(f)).
table(low_v_mind_maxp_minp,2,6,3,low(minp)).
table(low_v_mind_maxp_maxd,2,6,3,low(maxd)).
table(up_v_mind_maxp_minp,2,6,3,up(minp)).
table(up_v_mind_maxp_maxd,2,6,3,up(maxd)).
table(low_v_mind_maxp_f,2,6,3,low(f)).
table(up_v_mind_maxp_f,2,6,3,up(f)).
table(low_v_f_mind_maxp,2,6,3,low(maxp)).
table(low_v_f_mind_minp,2,6,3,low(minp)).
table(up_v_f_mind_maxp,2,6,3,up(maxp)).
table(up_v_f_mind_minp,2,6,3,up(minp)).
table(low_v_f_mind_maxd,2,6,3,low(maxd)).
table(up_v_f_mind_maxd,2,6,3,up(maxd)).
table(low_v_f_maxd_mind,2,6,3,low(mind)).
table(up_v_f_maxd_mind,2,6,3,up(mind)).
table(low_v_f_maxd_maxp,2,6,3,low(maxp)).
table(up_v_f_maxd_maxp,2,6,3,up(maxp)).
table(low_v_f_maxd_minp,2,6,3,low(minp)).
table(up_v_f_maxd_minp,2,6,3,up(minp)).
table(low_v_f_minp_maxd,2,6,3,low(maxd)).
table(up_v_f_minp_maxd,2,6,3,up(maxd)).
table(low_v_f_minp_mind,2,6,3,low(mind)).
table(up_v_f_minp_mind,2,6,3,up(mind)).
table(low_v_f_minp_maxp,2,6,3,low(maxp)).
table(up_v_f_minp_maxp,2,6,3,up(maxp)).
table(low_v_f_maxp_minp,2,6,3,low(minp)).
table(up_v_f_maxp_minp,2,6,3,up(minp)).
table(low_v_f_maxp_maxd,2,6,3,low(maxd)).
table(up_v_f_maxp_maxd,2,6,3,up(maxd)).
table(low_v_f_maxp_mind,2,6,3,low(mind)).
table(up_v_f_maxp_mind,2,6,3,up(mind)).
table(low_v_maxp,3,6,1,low(maxp)).
table(up_v_maxp,3,6,1,up(maxp)).
table(low_v_minp,3,6,1,low(minp)).
table(up_v_minp,3,6,1,up(minp)).
table(low_v_maxd,3,6,1,low(maxd)).
table(up_v_maxd,3,6,1,up(maxd)).
table(low_v_mind,3,6,1,low(mind)).
table(up_v_mind,3,6,1,up(mind)).
table(low_v_f,3,6,1,low(f)).
table(up_v_f,3,6,1,up(f)).
table(low_v_maxp_f,3,6,2,low(f)).
table(up_v_maxp_f,3,6,2,up(f)).
table(low_v_maxp_mind,3,6,2,low(mind)).
table(up_v_maxp_mind,3,6,2,up(mind)).
table(low_v_maxp_maxd,3,6,2,low(maxd)).
table(up_v_maxp_maxd,3,6,2,up(maxd)).
table(low_v_maxp_minp,3,6,2,low(minp)).
table(up_v_maxp_minp,3,6,2,up(minp)).
table(low_v_minp_maxp,3,6,2,low(maxp)).
table(up_v_minp_maxp,3,6,2,up(maxp)).
table(low_v_minp_f,3,6,2,low(f)).
table(up_v_minp_f,3,6,2,up(f)).
table(low_v_minp_mind,3,6,2,low(mind)).
table(up_v_minp_mind,3,6,2,up(mind)).
table(low_v_maxd_minp,3,6,2,low(minp)).
table(up_v_maxd_minp,3,6,2,up(minp)).
table(low_v_minp_maxd,3,6,2,low(maxd)).
table(up_v_minp_maxd,3,6,2,up(maxd)).
table(low_v_maxd_maxp,3,6,2,low(maxp)).
table(up_v_maxd_maxp,3,6,2,up(maxp)).
table(low_v_maxd_f,3,6,2,low(f)).
table(up_v_maxd_f,3,6,2,up(f)).
table(low_v_maxd_mind,3,6,2,low(mind)).
table(up_v_maxd_mind,3,6,2,up(mind)).
table(low_v_mind_maxd,3,6,2,low(maxd)).
table(up_v_mind_maxd,3,6,2,up(maxd)).
table(low_v_mind_maxp,3,6,2,low(maxp)).
table(up_v_mind_maxp,3,6,2,up(maxp)).
table(low_v_mind_minp,3,6,2,low(minp)).
table(up_v_mind_minp,3,6,2,up(minp)).
table(low_v_mind_f,3,6,2,low(f)).
table(up_v_mind_f,3,6,2,up(f)).
table(low_v_f_maxd,3,6,2,low(maxd)).
table(up_v_f_maxd,3,6,2,up(maxd)).
table(low_v_f_mind,3,6,2,low(mind)).
table(up_v_f_mind,3,6,2,up(mind)).
table(low_v_f_minp,3,6,2,low(minp)).
table(low_v_f_maxp,3,6,2,low(maxp)).
table(up_v_f_minp,3,6,2,up(minp)).
table(low_v_minp_maxp_f,3,6,3,low(f)).
table(up_v_f_maxp,3,6,2,up(maxp)).
table(up_v_minp_maxp_f,3,6,3,up(f)).
table(low_v_minp_maxp_mind,3,6,3,low(mind)).
table(up_v_minp_maxp_mind,3,6,3,up(mind)).
table(low_v_minp_maxp_maxd,3,6,3,low(maxd)).
table(up_v_minp_maxp_maxd,3,6,3,up(maxd)).
table(low_v_maxd_minp_maxp,3,6,3,low(maxp)).
table(up_v_maxd_minp_maxp,3,6,3,up(maxp)).
table(low_v_maxd_minp_f,3,6,3,low(f)).
table(up_v_maxd_minp_f,3,6,3,up(f)).
table(low_v_maxd_minp_mind,3,6,3,low(mind)).
table(up_v_maxd_minp_mind,3,6,3,up(mind)).
table(low_v_maxd_maxp_minp,3,6,3,low(minp)).
table(up_v_maxd_maxp_minp,3,6,3,up(minp)).
table(low_v_maxd_maxp_f,3,6,3,low(f)).
table(low_v_maxd_maxp_mind,3,6,3,low(mind)).
table(up_v_maxd_maxp_f,3,6,3,up(f)).
table(up_v_maxd_maxp_mind,3,6,3,up(mind)).
table(low_v_mind_maxd_maxp,3,6,3,low(maxp)).
table(up_v_mind_maxd_maxp,3,6,3,up(maxp)).
table(low_v_mind_maxd_minp,3,6,3,low(minp)).
table(up_v_mind_maxd_minp,3,6,3,up(minp)).
table(low_v_mind_maxd_f,3,6,3,low(f)).
table(low_v_mind_minp_maxd,3,6,3,low(maxd)).
table(up_v_mind_maxd_f,3,6,3,up(f)).
table(up_v_mind_minp_maxd,3,6,3,up(maxd)).
table(low_v_mind_minp_maxp,3,6,3,low(maxp)).
table(up_v_mind_minp_maxp,3,6,3,up(maxp)).
table(low_v_mind_minp_f,3,6,3,low(f)).
table(up_v_mind_minp_f,3,6,3,up(f)).
table(low_v_mind_maxp_minp,3,6,3,low(minp)).
table(up_v_mind_maxp_minp,3,6,3,up(minp)).
table(low_v_mind_maxp_maxd,3,6,3,low(maxd)).
table(up_v_mind_maxp_maxd,3,6,3,up(maxd)).
table(low_v_mind_maxp_f,3,6,3,low(f)).
table(up_v_mind_maxp_f,3,6,3,up(f)).
table(low_v_f_mind_maxp,3,6,3,low(maxp)).
table(up_v_f_mind_maxp,3,6,3,up(maxp)).
table(low_v_f_mind_minp,3,6,3,low(minp)).
table(up_v_f_mind_minp,3,6,3,up(minp)).
table(low_v_f_mind_maxd,3,6,3,low(maxd)).
table(up_v_f_mind_maxd,3,6,3,up(maxd)).
table(low_v_f_maxd_mind,3,6,3,low(mind)).
table(up_v_f_maxd_mind,3,6,3,up(mind)).
table(low_v_f_maxd_maxp,3,6,3,low(maxp)).
table(up_v_f_maxd_maxp,3,6,3,up(maxp)).
table(low_v_f_maxd_minp,3,6,3,low(minp)).
table(up_v_f_maxd_minp,3,6,3,up(minp)).
table(low_v_f_minp_maxd,3,6,3,low(maxd)).
table(up_v_f_minp_maxd,3,6,3,up(maxd)).
table(low_v_f_minp_mind,3,6,3,low(mind)).
table(up_v_f_minp_mind,3,6,3,up(mind)).
table(low_v_f_minp_maxp,3,6,3,low(maxp)).
table(up_v_f_minp_maxp,3,6,3,up(maxp)).
table(low_v_f_maxp_minp,3,6,3,low(minp)).
table(up_v_f_maxp_minp,3,6,3,up(minp)).
table(low_v_f_maxp_maxd,3,6,3,low(maxd)).
table(up_v_f_maxp_maxd,3,6,3,up(maxd)).
table(low_v_f_maxp_mind,3,6,3,low(mind)).
table(up_v_f_maxp_mind,3,6,3,up(mind)).
table(low_v_maxp,4,6,1,low(maxp)).
table(up_v_maxp,4,6,1,up(maxp)).
table(low_v_minp,4,6,1,low(minp)).
table(up_v_minp,4,6,1,up(minp)).
table(low_v_maxd,4,6,1,low(maxd)).
table(up_v_maxd,4,6,1,up(maxd)).
table(low_v_mind,4,6,1,low(mind)).
table(up_v_mind,4,6,1,up(mind)).
table(low_v_f,4,6,1,low(f)).
table(up_v_f,4,6,1,up(f)).
table(low_v_maxp_f,4,6,2,low(f)).
table(up_v_maxp_f,4,6,2,up(f)).
table(low_v_maxp_mind,4,6,2,low(mind)).
table(up_v_maxp_mind,4,6,2,up(mind)).
table(low_v_maxp_maxd,4,6,2,low(maxd)).
table(up_v_maxp_maxd,4,6,2,up(maxd)).
table(low_v_maxp_minp,4,6,2,low(minp)).
table(up_v_maxp_minp,4,6,2,up(minp)).
table(low_v_minp_maxp,4,6,2,low(maxp)).
table(up_v_minp_maxp,4,6,2,up(maxp)).
table(low_v_minp_f,4,6,2,low(f)).
table(up_v_minp_f,4,6,2,up(f)).
table(low_v_minp_mind,4,6,2,low(mind)).
table(up_v_minp_mind,4,6,2,up(mind)).
table(low_v_minp_maxd,4,6,2,low(maxd)).
table(up_v_minp_maxd,4,6,2,up(maxd)).
table(low_v_maxd_minp,4,6,2,low(minp)).
table(low_v_maxd_maxp,4,6,2,low(maxp)).
table(low_v_maxd_f,4,6,2,low(f)).
table(up_v_maxd_minp,4,6,2,up(minp)).
table(up_v_maxd_maxp,4,6,2,up(maxp)).
table(up_v_maxd_f,4,6,2,up(f)).
table(low_v_mind_maxd,4,6,2,low(maxd)).
table(up_v_mind_maxd,4,6,2,up(maxd)).
table(low_v_mind_minp,4,6,2,low(minp)).
table(low_v_maxd_mind,4,6,2,low(mind)).
table(up_v_mind_minp,4,6,2,up(minp)).
table(up_v_maxd_mind,4,6,2,up(mind)).
table(low_v_mind_maxp,4,6,2,low(maxp)).
table(up_v_mind_maxp,4,6,2,up(maxp)).
table(low_v_mind_f,4,6,2,low(f)).
table(up_v_mind_f,4,6,2,up(f)).
table(low_v_f_mind,4,6,2,low(mind)).
table(up_v_f_mind,4,6,2,up(mind)).
table(low_v_f_minp,4,6,2,low(minp)).
table(up_v_f_minp,4,6,2,up(minp)).
table(low_v_f_maxd,4,6,2,low(maxd)).
table(up_v_f_maxd,4,6,2,up(maxd)).
table(low_v_f_maxp,4,6,2,low(maxp)).
table(up_v_f_maxp,4,6,2,up(maxp)).
table(low_v_minp_maxp_f,4,6,3,low(f)).
table(up_v_minp_maxp_f,4,6,3,up(f)).
table(low_v_minp_maxp_mind,4,6,3,low(mind)).
table(up_v_minp_maxp_mind,4,6,3,up(mind)).
table(low_v_minp_maxp_maxd,4,6,3,low(maxd)).
table(up_v_minp_maxp_maxd,4,6,3,up(maxd)).
table(low_v_maxd_minp_maxp,4,6,3,low(maxp)).
table(up_v_maxd_minp_maxp,4,6,3,up(maxp)).
table(low_v_maxd_minp_mind,4,6,3,low(mind)).
table(up_v_maxd_minp_mind,4,6,3,up(mind)).
table(low_v_maxd_minp_f,4,6,3,low(f)).
table(up_v_maxd_minp_f,4,6,3,up(f)).
table(low_v_maxd_maxp_minp,4,6,3,low(minp)).
table(up_v_maxd_maxp_minp,4,6,3,up(minp)).
table(low_v_maxd_maxp_f,4,6,3,low(f)).
table(up_v_maxd_maxp_f,4,6,3,up(f)).
table(low_v_maxd_maxp_mind,4,6,3,low(mind)).
table(up_v_maxd_maxp_mind,4,6,3,up(mind)).
table(low_v_mind_maxd_maxp,4,6,3,low(maxp)).
table(up_v_mind_maxd_maxp,4,6,3,up(maxp)).
table(low_v_mind_maxd_minp,4,6,3,low(minp)).
table(low_v_mind_maxd_f,4,6,3,low(f)).
table(up_v_mind_maxd_minp,4,6,3,up(minp)).
table(up_v_mind_maxd_f,4,6,3,up(f)).
table(low_v_mind_minp_maxd,4,6,3,low(maxd)).
table(low_v_mind_minp_maxp,4,6,3,low(maxp)).
table(up_v_mind_minp_maxd,4,6,3,up(maxd)).
table(low_v_mind_minp_f,4,6,3,low(f)).
table(up_v_mind_minp_maxp,4,6,3,up(maxp)).
table(up_v_mind_minp_f,4,6,3,up(f)).
table(low_v_mind_maxp_minp,4,6,3,low(minp)).
table(up_v_mind_maxp_minp,4,6,3,up(minp)).
table(low_v_mind_maxp_maxd,4,6,3,low(maxd)).
table(up_v_mind_maxp_maxd,4,6,3,up(maxd)).
table(low_v_mind_maxp_f,4,6,3,low(f)).
table(up_v_mind_maxp_f,4,6,3,up(f)).
table(low_v_f_mind_maxp,4,6,3,low(maxp)).
table(up_v_f_mind_maxp,4,6,3,up(maxp)).
table(low_v_f_mind_minp,4,6,3,low(minp)).
table(up_v_f_mind_minp,4,6,3,up(minp)).
table(low_v_f_mind_maxd,4,6,3,low(maxd)).
table(up_v_f_mind_maxd,4,6,3,up(maxd)).
table(low_v_f_maxd_mind,4,6,3,low(mind)).
table(up_v_f_maxd_mind,4,6,3,up(mind)).
table(low_v_f_maxd_maxp,4,6,3,low(maxp)).
table(up_v_f_maxd_maxp,4,6,3,up(maxp)).
table(low_v_f_maxd_minp,4,6,3,low(minp)).
table(up_v_f_maxd_minp,4,6,3,up(minp)).
table(low_v_f_minp_maxd,4,6,3,low(maxd)).
table(up_v_f_minp_maxd,4,6,3,up(maxd)).
table(low_v_f_minp_mind,4,6,3,low(mind)).
table(up_v_f_minp_mind,4,6,3,up(mind)).
table(low_v_f_minp_maxp,4,6,3,low(maxp)).
table(up_v_f_minp_maxp,4,6,3,up(maxp)).
table(low_v_f_maxp_minp,4,6,3,low(minp)).
table(up_v_f_maxp_minp,4,6,3,up(minp)).
table(low_v_f_maxp_maxd,4,6,3,low(maxd)).
table(up_v_f_maxp_maxd,4,6,3,up(maxd)).
table(low_v_f_maxp_mind,4,6,3,low(mind)).
table(up_v_f_maxp_mind,4,6,3,up(mind)).
table(low_v_maxp,5,6,1,low(maxp)).
table(up_v_maxp,5,6,1,up(maxp)).
table(low_v_minp,5,6,1,low(minp)).
table(up_v_minp,5,6,1,up(minp)).
table(low_v_maxd,5,6,1,low(maxd)).
table(up_v_maxd,5,6,1,up(maxd)).
table(low_v_mind,5,6,1,low(mind)).
table(up_v_mind,5,6,1,up(mind)).
table(low_v_maxp_f,5,6,2,low(f)).
table(up_v_maxp_f,5,6,2,up(f)).
table(low_v_f,5,6,1,low(f)).
table(up_v_f,5,6,1,up(f)).
table(low_v_maxp_mind,5,6,2,low(mind)).
table(up_v_maxp_mind,5,6,2,up(mind)).
table(low_v_maxp_maxd,5,6,2,low(maxd)).
table(low_v_maxp_minp,5,6,2,low(minp)).
table(up_v_maxp_maxd,5,6,2,up(maxd)).
table(up_v_maxp_minp,5,6,2,up(minp)).
table(low_v_minp_maxp,5,6,2,low(maxp)).
table(up_v_minp_maxp,5,6,2,up(maxp)).
table(low_v_minp_f,5,6,2,low(f)).
table(up_v_minp_f,5,6,2,up(f)).
table(low_v_minp_mind,5,6,2,low(mind)).
table(up_v_minp_mind,5,6,2,up(mind)).
table(low_v_minp_maxd,5,6,2,low(maxd)).
table(low_v_maxd_minp,5,6,2,low(minp)).
table(up_v_minp_maxd,5,6,2,up(maxd)).
table(up_v_maxd_minp,5,6,2,up(minp)).
table(low_v_maxd_maxp,5,6,2,low(maxp)).
table(up_v_maxd_maxp,5,6,2,up(maxp)).
table(low_v_maxd_mind,5,6,2,low(mind)).
table(low_v_maxd_f,5,6,2,low(f)).
table(up_v_maxd_mind,5,6,2,up(mind)).
table(low_v_mind_maxd,5,6,2,low(maxd)).
table(up_v_maxd_f,5,6,2,up(f)).
table(up_v_mind_maxd,5,6,2,up(maxd)).
table(low_v_mind_maxp,5,6,2,low(maxp)).
table(low_v_mind_minp,5,6,2,low(minp)).
table(low_v_mind_f,5,6,2,low(f)).
table(up_v_mind_maxp,5,6,2,up(maxp)).
table(up_v_mind_minp,5,6,2,up(minp)).
table(up_v_mind_f,5,6,2,up(f)).
table(low_v_f_mind,5,6,2,low(mind)).
table(up_v_f_mind,5,6,2,up(mind)).
table(low_v_f_maxd,5,6,2,low(maxd)).
table(low_v_f_minp,5,6,2,low(minp)).
table(up_v_f_maxd,5,6,2,up(maxd)).
table(up_v_f_minp,5,6,2,up(minp)).
table(low_v_f_maxp,5,6,2,low(maxp)).
table(low_v_minp_maxp_mind,5,6,3,low(mind)).
table(up_v_f_maxp,5,6,2,up(maxp)).
table(up_v_minp_maxp_mind,5,6,3,up(mind)).
table(low_v_minp_maxp_f,5,6,3,low(f)).
table(up_v_minp_maxp_f,5,6,3,up(f)).
table(low_v_minp_maxp_maxd,5,6,3,low(maxd)).
table(low_v_maxd_minp_maxp,5,6,3,low(maxp)).
table(up_v_minp_maxp_maxd,5,6,3,up(maxd)).
table(low_v_maxd_minp_f,5,6,3,low(f)).
table(up_v_maxd_minp_maxp,5,6,3,up(maxp)).
table(up_v_maxd_minp_f,5,6,3,up(f)).
table(low_v_maxd_maxp_minp,5,6,3,low(minp)).
table(up_v_maxd_maxp_minp,5,6,3,up(minp)).
table(low_v_maxd_minp_mind,5,6,3,low(mind)).
table(low_v_maxd_maxp_f,5,6,3,low(f)).
table(up_v_maxd_minp_mind,5,6,3,up(mind)).
table(up_v_maxd_maxp_f,5,6,3,up(f)).
table(low_v_maxd_maxp_mind,5,6,3,low(mind)).
table(up_v_maxd_maxp_mind,5,6,3,up(mind)).
table(low_v_mind_maxd_minp,5,6,3,low(minp)).
table(up_v_mind_maxd_minp,5,6,3,up(minp)).
table(low_v_mind_maxd_maxp,5,6,3,low(maxp)).
table(up_v_mind_maxd_maxp,5,6,3,up(maxp)).
table(low_v_mind_maxd_f,5,6,3,low(f)).
table(up_v_mind_maxd_f,5,6,3,up(f)).
table(low_v_mind_minp_maxd,5,6,3,low(maxd)).
table(up_v_mind_minp_maxd,5,6,3,up(maxd)).
table(low_v_mind_minp_maxp,5,6,3,low(maxp)).
table(up_v_mind_minp_maxp,5,6,3,up(maxp)).
table(low_v_mind_minp_f,5,6,3,low(f)).
table(low_v_mind_maxp_minp,5,6,3,low(minp)).
table(up_v_mind_minp_f,5,6,3,up(f)).
table(up_v_mind_maxp_minp,5,6,3,up(minp)).
table(low_v_mind_maxp_maxd,5,6,3,low(maxd)).
table(up_v_mind_maxp_maxd,5,6,3,up(maxd)).
table(low_v_mind_maxp_f,5,6,3,low(f)).
table(up_v_mind_maxp_f,5,6,3,up(f)).
table(low_v_f_mind_maxp,5,6,3,low(maxp)).
table(low_v_f_mind_minp,5,6,3,low(minp)).
table(up_v_f_mind_maxp,5,6,3,up(maxp)).
table(up_v_f_mind_minp,5,6,3,up(minp)).
table(low_v_f_mind_maxd,5,6,3,low(maxd)).
table(up_v_f_mind_maxd,5,6,3,up(maxd)).
table(low_v_f_maxd_maxp,5,6,3,low(maxp)).
table(low_v_f_maxd_mind,5,6,3,low(mind)).
table(up_v_f_maxd_maxp,5,6,3,up(maxp)).
table(up_v_f_maxd_mind,5,6,3,up(mind)).
table(low_v_f_maxd_minp,5,6,3,low(minp)).
table(up_v_f_maxd_minp,5,6,3,up(minp)).
table(low_v_f_minp_mind,5,6,3,low(mind)).
table(up_v_f_minp_mind,5,6,3,up(mind)).
table(low_v_f_minp_maxd,5,6,3,low(maxd)).
table(up_v_f_minp_maxd,5,6,3,up(maxd)).
table(low_v_f_minp_maxp,5,6,3,low(maxp)).
table(low_v_f_maxp_minp,5,6,3,low(minp)).
table(up_v_f_minp_maxp,5,6,3,up(maxp)).
table(up_v_f_maxp_minp,5,6,3,up(minp)).
table(low_v_f_maxp_maxd,5,6,3,low(maxd)).
table(up_v_f_maxp_maxd,5,6,3,up(maxd)).
table(low_v_maxp,6,6,1,low(maxp)).
table(low_v_f_maxp_mind,5,6,3,low(mind)).
table(up_v_maxp,6,6,1,up(maxp)).
table(up_v_f_maxp_mind,5,6,3,up(mind)).
table(low_v_minp,6,6,1,low(minp)).
table(up_v_minp,6,6,1,up(minp)).
table(low_v_maxd,6,6,1,low(maxd)).
table(low_v_mind,6,6,1,low(mind)).
table(low_v_f,6,6,1,low(f)).
table(up_v_maxd,6,6,1,up(maxd)).
table(up_v_mind,6,6,1,up(mind)).
table(up_v_f,6,6,1,up(f)).
table(low_v_maxp_f,6,6,2,low(f)).
table(up_v_maxp_f,6,6,2,up(f)).
table(low_v_maxp_mind,6,6,2,low(mind)).
table(low_v_maxp_maxd,6,6,2,low(maxd)).
table(up_v_maxp_mind,6,6,2,up(mind)).
table(up_v_maxp_maxd,6,6,2,up(maxd)).
table(low_v_maxp_minp,6,6,2,low(minp)).
table(up_v_maxp_minp,6,6,2,up(minp)).
table(low_v_minp_maxp,6,6,2,low(maxp)).
table(low_v_minp_f,6,6,2,low(f)).
table(up_v_minp_maxp,6,6,2,up(maxp)).
table(up_v_minp_f,6,6,2,up(f)).
table(low_v_minp_mind,6,6,2,low(mind)).
table(low_v_minp_maxd,6,6,2,low(maxd)).
table(up_v_minp_mind,6,6,2,up(mind)).
table(up_v_minp_maxd,6,6,2,up(maxd)).
table(low_v_maxd_minp,6,6,2,low(minp)).
table(up_v_maxd_minp,6,6,2,up(minp)).
table(low_v_maxd_maxp,6,6,2,low(maxp)).
table(low_v_maxd_f,6,6,2,low(f)).
table(up_v_maxd_maxp,6,6,2,up(maxp)).
table(low_v_maxd_mind,6,6,2,low(mind)).
table(up_v_maxd_f,6,6,2,up(f)).
table(up_v_maxd_mind,6,6,2,up(mind)).
table(low_v_mind_maxd,6,6,2,low(maxd)).
table(up_v_mind_maxd,6,6,2,up(maxd)).
table(low_v_mind_maxp,6,6,2,low(maxp)).
table(low_v_mind_minp,6,6,2,low(minp)).
table(up_v_mind_maxp,6,6,2,up(maxp)).
table(up_v_mind_minp,6,6,2,up(minp)).
table(low_v_mind_f,6,6,2,low(f)).
table(low_v_f_mind,6,6,2,low(mind)).
table(up_v_mind_f,6,6,2,up(f)).
table(low_v_f_maxd,6,6,2,low(maxd)).
table(up_v_f_mind,6,6,2,up(mind)).
table(up_v_f_maxd,6,6,2,up(maxd)).
table(low_v_f_minp,6,6,2,low(minp)).
table(low_v_f_maxp,6,6,2,low(maxp)).
table(low_v_minp_maxp_f,6,6,3,low(f)).
table(up_v_f_minp,6,6,2,up(minp)).
table(up_v_f_maxp,6,6,2,up(maxp)).
table(up_v_minp_maxp_f,6,6,3,up(f)).
table(low_v_minp_maxp_mind,6,6,3,low(mind)).
table(low_v_minp_maxp_maxd,6,6,3,low(maxd)).
table(up_v_minp_maxp_mind,6,6,3,up(mind)).
table(low_v_maxd_minp_maxp,6,6,3,low(maxp)).
table(up_v_minp_maxp_maxd,6,6,3,up(maxd)).
table(up_v_maxd_minp_maxp,6,6,3,up(maxp)).
table(low_v_maxd_minp_f,6,6,3,low(f)).
table(up_v_maxd_minp_f,6,6,3,up(f)).
table(low_v_maxd_maxp_minp,6,6,3,low(minp)).
table(low_v_maxd_minp_mind,6,6,3,low(mind)).
table(up_v_maxd_maxp_minp,6,6,3,up(minp)).
table(up_v_maxd_minp_mind,6,6,3,up(mind)).
table(low_v_maxd_maxp_f,6,6,3,low(f)).
table(low_v_maxd_maxp_mind,6,6,3,low(mind)).
table(up_v_maxd_maxp_f,6,6,3,up(f)).
table(up_v_maxd_maxp_mind,6,6,3,up(mind)).
table(low_v_mind_maxd_maxp,6,6,3,low(maxp)).
table(up_v_mind_maxd_maxp,6,6,3,up(maxp)).
table(low_v_mind_maxd_minp,6,6,3,low(minp)).
table(low_v_mind_maxd_f,6,6,3,low(f)).
table(up_v_mind_maxd_minp,6,6,3,up(minp)).
table(up_v_mind_maxd_f,6,6,3,up(f)).
table(low_v_mind_minp_maxd,6,6,3,low(maxd)).
table(up_v_mind_minp_maxd,6,6,3,up(maxd)).
table(low_v_mind_minp_maxp,6,6,3,low(maxp)).
table(up_v_mind_minp_maxp,6,6,3,up(maxp)).
table(low_v_mind_maxp_minp,6,6,3,low(minp)).
table(up_v_mind_maxp_minp,6,6,3,up(minp)).
table(low_v_mind_minp_f,6,6,3,low(f)).
table(up_v_mind_minp_f,6,6,3,up(f)).
table(low_v_mind_maxp_maxd,6,6,3,low(maxd)).
table(low_v_mind_maxp_f,6,6,3,low(f)).
table(up_v_mind_maxp_maxd,6,6,3,up(maxd)).
table(low_v_f_mind_maxp,6,6,3,low(maxp)).
table(up_v_mind_maxp_f,6,6,3,up(f)).
table(up_v_f_mind_maxp,6,6,3,up(maxp)).
table(low_v_f_mind_minp,6,6,3,low(minp)).
table(up_v_f_mind_minp,6,6,3,up(minp)).
table(low_v_f_mind_maxd,6,6,3,low(maxd)).
table(low_v_f_maxd_mind,6,6,3,low(mind)).
table(up_v_f_mind_maxd,6,6,3,up(maxd)).
table(up_v_f_maxd_mind,6,6,3,up(mind)).
table(low_v_f_maxd_maxp,6,6,3,low(maxp)).
table(low_v_f_maxd_minp,6,6,3,low(minp)).
table(up_v_f_maxd_maxp,6,6,3,up(maxp)).
table(up_v_f_maxd_minp,6,6,3,up(minp)).
table(low_v_f_minp_maxd,6,6,3,low(maxd)).
table(up_v_f_minp_maxd,6,6,3,up(maxd)).
table(low_v_f_minp_mind,6,6,3,low(mind)).
table(low_v_f_minp_maxp,6,6,3,low(maxp)).
table(up_v_f_minp_mind,6,6,3,up(mind)).
table(low_v_f_maxp_minp,6,6,3,low(minp)).
table(up_v_f_minp_maxp,6,6,3,up(maxp)).
table(up_v_f_maxp_minp,6,6,3,up(minp)).
table(low_v_f_maxp_maxd,6,6,3,low(maxd)).
table(up_v_f_maxp_maxd,6,6,3,up(maxd)).
table(low_v_f_maxp_mind,6,6,3,low(mind)).
table(up_v_f_maxp_mind,6,6,3,up(mind)).
table(low_v_maxp,7,6,1,low(maxp)).
table(up_v_maxp,7,6,1,up(maxp)).
table(low_v_minp,7,6,1,low(minp)).
table(up_v_minp,7,6,1,up(minp)).
table(low_v_maxd,7,6,1,low(maxd)).
table(up_v_maxd,7,6,1,up(maxd)).
table(low_v_mind,7,6,1,low(mind)).
table(up_v_mind,7,6,1,up(mind)).
table(low_v_f,7,6,1,low(f)).
table(low_v_maxp_f,7,6,2,low(f)).
table(up_v_f,7,6,1,up(f)).
table(up_v_maxp_f,7,6,2,up(f)).
table(low_v_maxp_mind,7,6,2,low(mind)).
table(up_v_maxp_mind,7,6,2,up(mind)).
table(low_v_maxp_maxd,7,6,2,low(maxd)).
table(low_v_maxp_minp,7,6,2,low(minp)).
table(low_v_minp_maxp,7,6,2,low(maxp)).
table(up_v_maxp_maxd,7,6,2,up(maxd)).
table(up_v_maxp_minp,7,6,2,up(minp)).
table(up_v_minp_maxp,7,6,2,up(maxp)).
table(low_v_minp_f,7,6,2,low(f)).
table(low_v_minp_maxd,7,6,2,low(maxd)).
table(low_v_minp_mind,7,6,2,low(mind)).
table(up_v_minp_f,7,6,2,up(f)).
table(up_v_minp_maxd,7,6,2,up(maxd)).
table(up_v_minp_mind,7,6,2,up(mind)).
table(low_v_maxd_minp,7,6,2,low(minp)).
table(low_v_maxd_f,7,6,2,low(f)).
table(low_v_maxd_maxp,7,6,2,low(maxp)).
table(up_v_maxd_minp,7,6,2,up(minp)).
table(up_v_maxd_f,7,6,2,up(f)).
table(up_v_maxd_maxp,7,6,2,up(maxp)).
table(low_v_maxd_mind,7,6,2,low(mind)).
table(low_v_mind_maxd,7,6,2,low(maxd)).
table(up_v_maxd_mind,7,6,2,up(mind)).
table(up_v_mind_maxd,7,6,2,up(maxd)).
table(low_v_mind_minp,7,6,2,low(minp)).
table(up_v_mind_minp,7,6,2,up(minp)).
table(low_v_mind_maxp,7,6,2,low(maxp)).
table(low_v_mind_f,7,6,2,low(f)).
table(low_v_f_mind,7,6,2,low(mind)).
table(up_v_mind_maxp,7,6,2,up(maxp)).
table(up_v_mind_f,7,6,2,up(f)).
table(up_v_f_mind,7,6,2,up(mind)).
table(low_v_f_maxd,7,6,2,low(maxd)).
table(low_v_f_maxp,7,6,2,low(maxp)).
table(low_v_f_minp,7,6,2,low(minp)).
table(up_v_f_maxd,7,6,2,up(maxd)).
table(up_v_f_maxp,7,6,2,up(maxp)).
table(up_v_f_minp,7,6,2,up(minp)).
table(low_v_minp_maxp_f,7,6,3,low(f)).
table(low_v_minp_maxp_mind,7,6,3,low(mind)).
table(low_v_minp_maxp_maxd,7,6,3,low(maxd)).
table(up_v_minp_maxp_f,7,6,3,up(f)).
table(up_v_minp_maxp_mind,7,6,3,up(mind)).
table(up_v_minp_maxp_maxd,7,6,3,up(maxd)).
table(low_v_maxd_minp_maxp,7,6,3,low(maxp)).
table(low_v_maxd_minp_f,7,6,3,low(f)).
table(low_v_maxd_minp_mind,7,6,3,low(mind)).
table(up_v_maxd_minp_maxp,7,6,3,up(maxp)).
table(up_v_maxd_minp_f,7,6,3,up(f)).
table(up_v_maxd_minp_mind,7,6,3,up(mind)).
table(low_v_maxd_maxp_minp,7,6,3,low(minp)).
table(low_v_maxd_maxp_f,7,6,3,low(f)).
table(up_v_maxd_maxp_minp,7,6,3,up(minp)).
table(up_v_maxd_maxp_f,7,6,3,up(f)).
table(low_v_maxd_maxp_mind,7,6,3,low(mind)).
table(up_v_maxd_maxp_mind,7,6,3,up(mind)).
table(low_v_mind_maxd_minp,7,6,3,low(minp)).
table(low_v_mind_maxd_maxp,7,6,3,low(maxp)).
table(low_v_mind_maxd_f,7,6,3,low(f)).
table(up_v_mind_maxd_minp,7,6,3,up(minp)).
table(up_v_mind_maxd_maxp,7,6,3,up(maxp)).
table(up_v_mind_maxd_f,7,6,3,up(f)).
table(low_v_mind_minp_maxd,7,6,3,low(maxd)).
table(low_v_mind_minp_f,7,6,3,low(f)).
table(low_v_mind_minp_maxp,7,6,3,low(maxp)).
table(up_v_mind_minp_maxd,7,6,3,up(maxd)).
table(up_v_mind_minp_f,7,6,3,up(f)).
table(up_v_mind_minp_maxp,7,6,3,up(maxp)).
table(low_v_mind_maxp_f,7,6,3,low(f)).
table(low_v_mind_maxp_maxd,7,6,3,low(maxd)).
table(low_v_mind_maxp_minp,7,6,3,low(minp)).
table(up_v_mind_maxp_f,7,6,3,up(f)).
table(up_v_mind_maxp_maxd,7,6,3,up(maxd)).
table(up_v_mind_maxp_minp,7,6,3,up(minp)).
table(low_v_f_mind_maxp,7,6,3,low(maxp)).
table(low_v_f_mind_minp,7,6,3,low(minp)).
table(up_v_f_mind_maxp,7,6,3,up(maxp)).
table(low_v_f_mind_maxd,7,6,3,low(maxd)).
table(up_v_f_mind_minp,7,6,3,up(minp)).
table(up_v_f_mind_maxd,7,6,3,up(maxd)).
table(low_v_f_maxd_mind,7,6,3,low(mind)).
table(low_v_f_maxd_maxp,7,6,3,low(maxp)).
table(low_v_f_maxd_minp,7,6,3,low(minp)).
table(up_v_f_maxd_mind,7,6,3,up(mind)).
table(up_v_f_maxd_maxp,7,6,3,up(maxp)).
table(up_v_f_maxd_minp,7,6,3,up(minp)).
table(low_v_f_minp_maxd,7,6,3,low(maxd)).
table(low_v_f_minp_mind,7,6,3,low(mind)).
table(low_v_f_minp_maxp,7,6,3,low(maxp)).
table(up_v_f_minp_maxd,7,6,3,up(maxd)).
table(up_v_f_minp_maxp,7,6,3,up(maxp)).
table(up_v_f_minp_mind,7,6,3,up(mind)).
table(low_v_f_maxp_minp,7,6,3,low(minp)).
table(low_v_f_maxp_maxd,7,6,3,low(maxd)).
table(up_v_f_maxp_minp,7,6,3,up(minp)).
table(low_v_f_maxp_mind,7,6,3,low(mind)).
table(up_v_f_maxp_maxd,7,6,3,up(maxd)).
table(up_v_f_maxp_mind,7,6,3,up(mind)).
table(low_v_maxp,8,6,1,low(maxp)).
table(low_v_minp,8,6,1,low(minp)).
table(low_v_maxd,8,6,1,low(maxd)).
table(up_v_maxp,8,6,1,up(maxp)).
table(up_v_minp,8,6,1,up(minp)).
table(up_v_maxd,8,6,1,up(maxd)).
table(low_v_mind,8,6,1,low(mind)).
table(low_v_f,8,6,1,low(f)).
table(low_v_maxp_f,8,6,2,low(f)).
table(up_v_mind,8,6,1,up(mind)).
table(up_v_f,8,6,1,up(f)).
table(up_v_maxp_f,8,6,2,up(f)).
table(low_v_maxp_mind,8,6,2,low(mind)).
table(low_v_maxp_maxd,8,6,2,low(maxd)).
table(low_v_maxp_minp,8,6,2,low(minp)).
table(up_v_maxp_mind,8,6,2,up(mind)).
table(up_v_maxp_minp,8,6,2,up(minp)).
table(up_v_maxp_maxd,8,6,2,up(maxd)).
table(low_v_minp_maxp,8,6,2,low(maxp)).
table(low_v_minp_f,8,6,2,low(f)).
table(low_v_minp_mind,8,6,2,low(mind)).
table(up_v_minp_maxp,8,6,2,up(maxp)).
table(up_v_minp_f,8,6,2,up(f)).
table(up_v_minp_mind,8,6,2,up(mind)).
table(low_v_minp_maxd,8,6,2,low(maxd)).
table(low_v_maxd_minp,8,6,2,low(minp)).
table(low_v_maxd_maxp,8,6,2,low(maxp)).
table(up_v_minp_maxd,8,6,2,up(maxd)).
table(up_v_maxd_minp,8,6,2,up(minp)).
table(up_v_maxd_maxp,8,6,2,up(maxp)).
table(low_v_maxd_f,8,6,2,low(f)).
table(low_v_mind_maxd,8,6,2,low(maxd)).
table(low_v_maxd_mind,8,6,2,low(mind)).
table(up_v_maxd_f,8,6,2,up(f)).
table(up_v_mind_maxd,8,6,2,up(maxd)).
table(up_v_maxd_mind,8,6,2,up(mind)).
table(low_v_mind_minp,8,6,2,low(minp)).
table(low_v_mind_maxp,8,6,2,low(maxp)).
table(low_v_mind_f,8,6,2,low(f)).
table(up_v_mind_minp,8,6,2,up(minp)).
table(up_v_mind_maxp,8,6,2,up(maxp)).
table(up_v_mind_f,8,6,2,up(f)).
table(low_v_f_mind,8,6,2,low(mind)).
table(low_v_f_maxd,8,6,2,low(maxd)).
table(low_v_f_minp,8,6,2,low(minp)).
table(up_v_f_mind,8,6,2,up(mind)).
table(up_v_f_maxd,8,6,2,up(maxd)).
table(up_v_f_minp,8,6,2,up(minp)).
table(low_v_f_maxp,8,6,2,low(maxp)).
table(low_v_minp_maxp_mind,8,6,3,low(mind)).
table(low_v_minp_maxp_f,8,6,3,low(f)).
table(up_v_f_maxp,8,6,2,up(maxp)).
table(up_v_minp_maxp_mind,8,6,3,up(mind)).
table(up_v_minp_maxp_f,8,6,3,up(f)).
table(low_v_minp_maxp_maxd,8,6,3,low(maxd)).
table(low_v_maxd_minp_maxp,8,6,3,low(maxp)).
table(low_v_maxd_minp_f,8,6,3,low(f)).
table(up_v_minp_maxp_maxd,8,6,3,up(maxd)).
table(up_v_maxd_minp_maxp,8,6,3,up(maxp)).
table(up_v_maxd_minp_f,8,6,3,up(f)).
table(low_v_maxd_minp_mind,8,6,3,low(mind)).
table(low_v_maxd_maxp_minp,8,6,3,low(minp)).
table(low_v_maxd_maxp_f,8,6,3,low(f)).
table(up_v_maxd_minp_mind,8,6,3,up(mind)).
table(up_v_maxd_maxp_minp,8,6,3,up(minp)).
table(up_v_maxd_maxp_f,8,6,3,up(f)).
table(low_v_maxd_maxp_mind,8,6,3,low(mind)).
table(low_v_mind_maxd_maxp,8,6,3,low(maxp)).
table(low_v_mind_maxd_minp,8,6,3,low(minp)).
table(up_v_maxd_maxp_mind,8,6,3,up(mind)).
table(up_v_mind_maxd_maxp,8,6,3,up(maxp)).
table(up_v_mind_maxd_minp,8,6,3,up(minp)).
table(low_v_mind_maxd_f,8,6,3,low(f)).
table(low_v_mind_minp_maxd,8,6,3,low(maxd)).
table(low_v_mind_minp_maxp,8,6,3,low(maxp)).
table(up_v_mind_maxd_f,8,6,3,up(f)).
table(up_v_mind_minp_maxd,8,6,3,up(maxd)).
table(up_v_mind_minp_maxp,8,6,3,up(maxp)).
table(low_v_mind_minp_f,8,6,3,low(f)).
table(low_v_mind_maxp_minp,8,6,3,low(minp)).
table(low_v_mind_maxp_maxd,8,6,3,low(maxd)).
table(up_v_mind_minp_f,8,6,3,up(f)).
table(up_v_mind_maxp_minp,8,6,3,up(minp)).
table(up_v_mind_maxp_maxd,8,6,3,up(maxd)).
table(low_v_mind_maxp_f,8,6,3,low(f)).
table(low_v_f_mind_minp,8,6,3,low(minp)).
table(low_v_f_mind_maxp,8,6,3,low(maxp)).
table(up_v_mind_maxp_f,8,6,3,up(f)).
table(up_v_f_mind_minp,8,6,3,up(minp)).
table(up_v_f_mind_maxp,8,6,3,up(maxp)).
table(low_v_f_mind_maxd,8,6,3,low(maxd)).
table(low_v_f_maxd_mind,8,6,3,low(mind)).
table(low_v_f_maxd_maxp,8,6,3,low(maxp)).
table(up_v_f_mind_maxd,8,6,3,up(maxd)).
table(up_v_f_maxd_mind,8,6,3,up(mind)).
table(up_v_f_maxd_maxp,8,6,3,up(maxp)).
table(low_v_f_maxd_minp,8,6,3,low(minp)).
table(low_v_f_minp_maxd,8,6,3,low(maxd)).
table(low_v_f_minp_mind,8,6,3,low(mind)).
table(up_v_f_maxd_minp,8,6,3,up(minp)).
table(up_v_f_minp_maxd,8,6,3,up(maxd)).
table(up_v_f_minp_mind,8,6,3,up(mind)).
table(low_v_f_minp_maxp,8,6,3,low(maxp)).
table(low_v_f_maxp_minp,8,6,3,low(minp)).
table(low_v_f_maxp_maxd,8,6,3,low(maxd)).
table(up_v_f_minp_maxp,8,6,3,up(maxp)).
table(up_v_f_maxp_minp,8,6,3,up(minp)).
table(up_v_f_maxp_maxd,8,6,3,up(maxd)).
table(low_v_f_maxp_mind,8,6,3,low(mind)).
table(up_v_f_maxp_mind,8,6,3,up(mind)).
table(low_v_maxp,9,6,1,low(maxp)).
table(low_v_minp,9,6,1,low(minp)).
table(up_v_maxp,9,6,1,up(maxp)).
table(up_v_minp,9,6,1,up(minp)).
table(low_v_maxd,9,6,1,low(maxd)).
table(up_v_maxd,9,6,1,up(maxd)).
table(low_v_mind,9,6,1,low(mind)).
table(low_v_f,9,6,1,low(f)).
table(up_v_mind,9,6,1,up(mind)).
table(up_v_f,9,6,1,up(f)).
table(low_v_maxp_f,9,6,2,low(f)).
table(up_v_maxp_f,9,6,2,up(f)).
table(low_v_maxp_maxd,9,6,2,low(maxd)).
table(low_v_maxp_mind,9,6,2,low(mind)).
table(up_v_maxp_maxd,9,6,2,up(maxd)).
table(up_v_maxp_mind,9,6,2,up(mind)).
table(low_v_maxp_minp,9,6,2,low(minp)).
table(up_v_maxp_minp,9,6,2,up(minp)).
table(low_v_minp_maxp,9,6,2,low(maxp)).
table(low_v_minp_f,9,6,2,low(f)).
table(up_v_minp_maxp,9,6,2,up(maxp)).
table(up_v_minp_f,9,6,2,up(f)).
table(low_v_minp_mind,9,6,2,low(mind)).
table(up_v_minp_mind,9,6,2,up(mind)).
table(low_v_minp_maxd,9,6,2,low(maxd)).
table(low_v_maxd_minp,9,6,2,low(minp)).
table(up_v_minp_maxd,9,6,2,up(maxd)).
table(up_v_maxd_minp,9,6,2,up(minp)).
table(low_v_maxd_maxp,9,6,2,low(maxp)).
table(up_v_maxd_maxp,9,6,2,up(maxp)).
table(low_v_maxd_f,9,6,2,low(f)).
table(low_v_maxd_mind,9,6,2,low(mind)).
table(up_v_maxd_f,9,6,2,up(f)).
table(up_v_maxd_mind,9,6,2,up(mind)).
table(low_v_mind_maxd,9,6,2,low(maxd)).
table(up_v_mind_maxd,9,6,2,up(maxd)).
table(low_v_mind_minp,9,6,2,low(minp)).
table(low_v_mind_maxp,9,6,2,low(maxp)).
table(up_v_mind_minp,9,6,2,up(minp)).
table(up_v_mind_maxp,9,6,2,up(maxp)).
table(low_v_mind_f,9,6,2,low(f)).
table(up_v_mind_f,9,6,2,up(f)).
table(low_v_f_mind,9,6,2,low(mind)).
table(low_v_f_maxd,9,6,2,low(maxd)).
table(up_v_f_mind,9,6,2,up(mind)).
table(up_v_f_maxd,9,6,2,up(maxd)).
table(low_v_f_minp,9,6,2,low(minp)).
table(up_v_f_minp,9,6,2,up(minp)).
table(low_v_f_maxp,9,6,2,low(maxp)).
table(low_v_minp_maxp_f,9,6,3,low(f)).
table(up_v_f_maxp,9,6,2,up(maxp)).
table(up_v_minp_maxp_f,9,6,3,up(f)).
table(low_v_minp_maxp_mind,9,6,3,low(mind)).
table(up_v_minp_maxp_mind,9,6,3,up(mind)).
table(low_v_minp_maxp_maxd,9,6,3,low(maxd)).
table(low_v_maxd_minp_maxp,9,6,3,low(maxp)).
table(up_v_minp_maxp_maxd,9,6,3,up(maxd)).
table(up_v_maxd_minp_maxp,9,6,3,up(maxp)).
table(low_v_maxd_minp_f,9,6,3,low(f)).
table(up_v_maxd_minp_f,9,6,3,up(f)).
table(low_v_maxd_minp_mind,9,6,3,low(mind)).
table(low_v_maxd_maxp_minp,9,6,3,low(minp)).
table(up_v_maxd_minp_mind,9,6,3,up(mind)).
table(up_v_maxd_maxp_minp,9,6,3,up(minp)).
table(low_v_maxd_maxp_f,9,6,3,low(f)).
table(up_v_maxd_maxp_f,9,6,3,up(f)).
table(low_v_maxd_maxp_mind,9,6,3,low(mind)).
table(low_v_mind_maxd_maxp,9,6,3,low(maxp)).
table(up_v_maxd_maxp_mind,9,6,3,up(mind)).
table(up_v_mind_maxd_maxp,9,6,3,up(maxp)).
table(low_v_mind_maxd_minp,9,6,3,low(minp)).
table(up_v_mind_maxd_minp,9,6,3,up(minp)).
table(low_v_mind_maxd_f,9,6,3,low(f)).
table(low_v_mind_minp_maxd,9,6,3,low(maxd)).
table(up_v_mind_maxd_f,9,6,3,up(f)).
table(up_v_mind_minp_maxd,9,6,3,up(maxd)).
table(low_v_mind_minp_maxp,9,6,3,low(maxp)).
table(up_v_mind_minp_maxp,9,6,3,up(maxp)).
table(low_v_mind_minp_f,9,6,3,low(f)).
table(low_v_mind_maxp_minp,9,6,3,low(minp)).
table(up_v_mind_minp_f,9,6,3,up(f)).
table(up_v_mind_maxp_minp,9,6,3,up(minp)).
table(low_v_mind_maxp_maxd,9,6,3,low(maxd)).
table(up_v_mind_maxp_maxd,9,6,3,up(maxd)).
table(low_v_mind_maxp_f,9,6,3,low(f)).
table(low_v_f_mind_maxp,9,6,3,low(maxp)).
table(up_v_mind_maxp_f,9,6,3,up(f)).
table(up_v_f_mind_maxp,9,6,3,up(maxp)).
table(low_v_f_mind_minp,9,6,3,low(minp)).
table(up_v_f_mind_minp,9,6,3,up(minp)).
table(low_v_f_mind_maxd,9,6,3,low(maxd)).
table(low_v_f_maxd_mind,9,6,3,low(mind)).
table(up_v_f_mind_maxd,9,6,3,up(maxd)).
table(up_v_f_maxd_mind,9,6,3,up(mind)).
table(low_v_f_maxd_maxp,9,6,3,low(maxp)).
table(up_v_f_maxd_maxp,9,6,3,up(maxp)).
table(low_v_f_maxd_minp,9,6,3,low(minp)).
table(low_v_f_minp_maxd,9,6,3,low(maxd)).
table(up_v_f_maxd_minp,9,6,3,up(minp)).
table(up_v_f_minp_maxd,9,6,3,up(maxd)).
table(low_v_f_minp_mind,9,6,3,low(mind)).
table(up_v_f_minp_mind,9,6,3,up(mind)).
table(low_v_f_minp_maxp,9,6,3,low(maxp)).
table(low_v_f_maxp_minp,9,6,3,low(minp)).
table(up_v_f_minp_maxp,9,6,3,up(maxp)).
table(up_v_f_maxp_minp,9,6,3,up(minp)).
table(low_v_f_maxp_maxd,9,6,3,low(maxd)).
table(up_v_f_maxp_maxd,9,6,3,up(maxd)).
table(low_v_f_maxp_mind,9,6,3,low(mind)).
table(up_v_f_maxp_mind,9,6,3,up(mind)).
table(low_v_maxp,10,6,1,low(maxp)).
table(up_v_maxp,10,6,1,up(maxp)).
table(low_v_minp,10,6,1,low(minp)).
table(up_v_minp,10,6,1,up(minp)).
table(low_v_maxd,10,6,1,low(maxd)).
table(up_v_maxd,10,6,1,up(maxd)).
table(low_v_mind,10,6,1,low(mind)).
table(up_v_mind,10,6,1,up(mind)).
table(low_v_f,10,6,1,low(f)).
table(up_v_f,10,6,1,up(f)).
table(low_v_maxp_f,10,6,2,low(f)).
table(up_v_maxp_f,10,6,2,up(f)).
table(low_v_maxp_mind,10,6,2,low(mind)).
table(up_v_maxp_mind,10,6,2,up(mind)).
table(low_v_maxp_maxd,10,6,2,low(maxd)).
table(up_v_maxp_maxd,10,6,2,up(maxd)).
table(low_v_maxp_minp,10,6,2,low(minp)).
table(up_v_maxp_minp,10,6,2,up(minp)).
table(low_v_minp_maxp,10,6,2,low(maxp)).
table(up_v_minp_maxp,10,6,2,up(maxp)).
table(low_v_minp_f,10,6,2,low(f)).
table(up_v_minp_f,10,6,2,up(f)).
table(low_v_minp_mind,10,6,2,low(mind)).
table(up_v_minp_mind,10,6,2,up(mind)).
table(low_v_minp_maxd,10,6,2,low(maxd)).
table(up_v_minp_maxd,10,6,2,up(maxd)).
table(low_v_maxd_minp,10,6,2,low(minp)).
table(up_v_maxd_minp,10,6,2,up(minp)).
table(low_v_maxd_maxp,10,6,2,low(maxp)).
table(up_v_maxd_maxp,10,6,2,up(maxp)).
table(low_v_maxd_f,10,6,2,low(f)).
table(up_v_maxd_f,10,6,2,up(f)).
table(low_v_maxd_mind,10,6,2,low(mind)).
table(up_v_maxd_mind,10,6,2,up(mind)).
table(low_v_mind_maxd,10,6,2,low(maxd)).
table(up_v_mind_maxd,10,6,2,up(maxd)).
table(low_v_mind_minp,10,6,2,low(minp)).
table(up_v_mind_minp,10,6,2,up(minp)).
table(low_v_mind_maxp,10,6,2,low(maxp)).
table(up_v_mind_maxp,10,6,2,up(maxp)).
table(low_v_mind_f,10,6,2,low(f)).
table(up_v_mind_f,10,6,2,up(f)).
table(low_v_f_mind,10,6,2,low(mind)).
table(up_v_f_mind,10,6,2,up(mind)).
table(low_v_f_maxd,10,6,2,low(maxd)).
table(up_v_f_maxd,10,6,2,up(maxd)).
table(low_v_f_minp,10,6,2,low(minp)).
table(up_v_f_minp,10,6,2,up(minp)).
table(low_v_f_maxp,10,6,2,low(maxp)).
table(up_v_f_maxp,10,6,2,up(maxp)).
table(low_v_minp_maxp_f,10,6,3,low(f)).
table(up_v_minp_maxp_f,10,6,3,up(f)).
table(low_v_minp_maxp_mind,10,6,3,low(mind)).
table(up_v_minp_maxp_mind,10,6,3,up(mind)).
table(low_v_minp_maxp_maxd,10,6,3,low(maxd)).
table(up_v_minp_maxp_maxd,10,6,3,up(maxd)).
table(low_v_maxd_minp_maxp,10,6,3,low(maxp)).
table(up_v_maxd_minp_maxp,10,6,3,up(maxp)).
table(low_v_maxd_minp_f,10,6,3,low(f)).
table(up_v_maxd_minp_f,10,6,3,up(f)).
table(low_v_maxd_minp_mind,10,6,3,low(mind)).
table(up_v_maxd_minp_mind,10,6,3,up(mind)).
table(low_v_maxd_maxp_minp,10,6,3,low(minp)).
table(up_v_maxd_maxp_minp,10,6,3,up(minp)).
table(low_v_maxd_maxp_f,10,6,3,low(f)).
table(up_v_maxd_maxp_f,10,6,3,up(f)).
table(low_v_maxd_maxp_mind,10,6,3,low(mind)).
table(up_v_maxd_maxp_mind,10,6,3,up(mind)).
table(low_v_mind_maxd_maxp,10,6,3,low(maxp)).
table(up_v_mind_maxd_maxp,10,6,3,up(maxp)).
table(low_v_mind_maxd_minp,10,6,3,low(minp)).
table(up_v_mind_maxd_minp,10,6,3,up(minp)).
table(low_v_mind_maxd_f,10,6,3,low(f)).
table(up_v_mind_maxd_f,10,6,3,up(f)).
table(low_v_mind_minp_maxd,10,6,3,low(maxd)).
table(up_v_mind_minp_maxd,10,6,3,up(maxd)).
table(low_v_mind_minp_maxp,10,6,3,low(maxp)).
table(up_v_mind_minp_maxp,10,6,3,up(maxp)).
table(low_v_mind_minp_f,10,6,3,low(f)).
table(up_v_mind_minp_f,10,6,3,up(f)).
table(low_v_mind_maxp_minp,10,6,3,low(minp)).
table(up_v_mind_maxp_minp,10,6,3,up(minp)).
table(low_v_mind_maxp_maxd,10,6,3,low(maxd)).
table(up_v_mind_maxp_maxd,10,6,3,up(maxd)).
table(low_v_mind_maxp_f,10,6,3,low(f)).
table(up_v_mind_maxp_f,10,6,3,up(f)).
table(low_v_f_mind_maxp,10,6,3,low(maxp)).
table(up_v_f_mind_maxp,10,6,3,up(maxp)).
table(low_v_f_mind_minp,10,6,3,low(minp)).
table(up_v_f_mind_minp,10,6,3,up(minp)).
table(low_v_f_mind_maxd,10,6,3,low(maxd)).
table(up_v_f_mind_maxd,10,6,3,up(maxd)).
table(low_v_f_maxd_mind,10,6,3,low(mind)).
table(up_v_f_maxd_mind,10,6,3,up(mind)).
table(low_v_f_maxd_maxp,10,6,3,low(maxp)).
table(up_v_f_maxd_maxp,10,6,3,up(maxp)).
table(low_v_f_maxd_minp,10,6,3,low(minp)).
table(up_v_f_maxd_minp,10,6,3,up(minp)).
table(low_v_f_minp_maxd,10,6,3,low(maxd)).
table(up_v_f_minp_maxd,10,6,3,up(maxd)).
table(low_v_f_minp_mind,10,6,3,low(mind)).
table(up_v_f_minp_mind,10,6,3,up(mind)).
table(low_v_f_minp_maxp,10,6,3,low(maxp)).
table(up_v_f_minp_maxp,10,6,3,up(maxp)).
table(low_v_f_maxp_minp,10,6,3,low(minp)).
table(up_v_f_maxp_minp,10,6,3,up(minp)).
table(low_v_f_maxp_maxd,10,6,3,low(maxd)).
table(up_v_f_maxp_maxd,10,6,3,up(maxd)).
table(low_v_f_maxp_mind,10,6,3,low(mind)).
table(up_v_f_maxp_mind,10,6,3,up(mind)).
table(low_v_maxp,11,6,1,low(maxp)).
table(up_v_maxp,11,6,1,up(maxp)).
table(low_v_minp,11,6,1,low(minp)).
table(low_v_maxd,11,6,1,low(maxd)).
table(up_v_minp,11,6,1,up(minp)).
table(up_v_maxd,11,6,1,up(maxd)).
table(low_v_mind,11,6,1,low(mind)).
table(up_v_mind,11,6,1,up(mind)).
table(low_v_f,11,6,1,low(f)).
table(low_v_maxp_f,11,6,2,low(f)).
table(up_v_f,11,6,1,up(f)).
table(up_v_maxp_f,11,6,2,up(f)).
table(low_v_maxp_mind,11,6,2,low(mind)).
table(up_v_maxp_mind,11,6,2,up(mind)).
table(low_v_maxp_maxd,11,6,2,low(maxd)).
table(low_v_maxp_minp,11,6,2,low(minp)).
table(up_v_maxp_maxd,11,6,2,up(maxd)).
table(up_v_maxp_minp,11,6,2,up(minp)).
table(low_v_minp_maxp,11,6,2,low(maxp)).
table(up_v_minp_maxp,11,6,2,up(maxp)).
table(low_v_minp_f,11,6,2,low(f)).
table(low_v_minp_mind,11,6,2,low(mind)).
table(up_v_minp_f,11,6,2,up(f)).
table(up_v_minp_mind,11,6,2,up(mind)).
table(low_v_minp_maxd,11,6,2,low(maxd)).
table(up_v_minp_maxd,11,6,2,up(maxd)).
table(low_v_maxd_minp,11,6,2,low(minp)).
table(low_v_maxd_maxp,11,6,2,low(maxp)).
table(up_v_maxd_minp,11,6,2,up(minp)).
table(up_v_maxd_maxp,11,6,2,up(maxp)).
table(low_v_maxd_f,11,6,2,low(f)).
table(up_v_maxd_f,11,6,2,up(f)).
table(low_v_maxd_mind,11,6,2,low(mind)).
table(low_v_mind_maxd,11,6,2,low(maxd)).
table(up_v_maxd_mind,11,6,2,up(mind)).
table(up_v_mind_maxd,11,6,2,up(maxd)).
table(low_v_mind_minp,11,6,2,low(minp)).
table(up_v_mind_minp,11,6,2,up(minp)).
table(low_v_mind_maxp,11,6,2,low(maxp)).
table(low_v_mind_f,11,6,2,low(f)).
table(up_v_mind_maxp,11,6,2,up(maxp)).
table(up_v_mind_f,11,6,2,up(f)).
table(low_v_f_mind,11,6,2,low(mind)).
table(up_v_f_mind,11,6,2,up(mind)).
table(low_v_f_maxd,11,6,2,low(maxd)).
table(low_v_f_minp,11,6,2,low(minp)).
table(up_v_f_maxd,11,6,2,up(maxd)).
table(up_v_f_minp,11,6,2,up(minp)).
table(low_v_f_maxp,11,6,2,low(maxp)).
table(up_v_f_maxp,11,6,2,up(maxp)).
table(low_v_minp_maxp_f,11,6,3,low(f)).
table(low_v_minp_maxp_mind,11,6,3,low(mind)).
table(up_v_minp_maxp_f,11,6,3,up(f)).
table(up_v_minp_maxp_mind,11,6,3,up(mind)).
table(low_v_minp_maxp_maxd,11,6,3,low(maxd)).
table(up_v_minp_maxp_maxd,11,6,3,up(maxd)).
table(low_v_maxd_minp_maxp,11,6,3,low(maxp)).
table(low_v_maxd_minp_f,11,6,3,low(f)).
table(up_v_maxd_minp_maxp,11,6,3,up(maxp)).
table(up_v_maxd_minp_f,11,6,3,up(f)).
table(low_v_maxd_minp_mind,11,6,3,low(mind)).
table(up_v_maxd_minp_mind,11,6,3,up(mind)).
table(low_v_maxd_maxp_minp,11,6,3,low(minp)).
table(low_v_maxd_maxp_f,11,6,3,low(f)).
table(up_v_maxd_maxp_minp,11,6,3,up(minp)).
table(up_v_maxd_maxp_f,11,6,3,up(f)).
table(low_v_maxd_maxp_mind,11,6,3,low(mind)).
table(up_v_maxd_maxp_mind,11,6,3,up(mind)).
table(low_v_mind_maxd_maxp,11,6,3,low(maxp)).
table(low_v_mind_maxd_minp,11,6,3,low(minp)).
table(up_v_mind_maxd_maxp,11,6,3,up(maxp)).
table(up_v_mind_maxd_minp,11,6,3,up(minp)).
table(low_v_mind_maxd_f,11,6,3,low(f)).
table(up_v_mind_maxd_f,11,6,3,up(f)).
table(low_v_mind_minp_maxd,11,6,3,low(maxd)).
table(low_v_mind_minp_maxp,11,6,3,low(maxp)).
table(up_v_mind_minp_maxd,11,6,3,up(maxd)).
table(up_v_mind_minp_maxp,11,6,3,up(maxp)).
table(low_v_mind_minp_f,11,6,3,low(f)).
table(up_v_mind_minp_f,11,6,3,up(f)).
table(low_v_mind_maxp_minp,11,6,3,low(minp)).
table(low_v_mind_maxp_maxd,11,6,3,low(maxd)).
table(up_v_mind_maxp_minp,11,6,3,up(minp)).
table(up_v_mind_maxp_maxd,11,6,3,up(maxd)).
table(low_v_mind_maxp_f,11,6,3,low(f)).
table(up_v_mind_maxp_f,11,6,3,up(f)).
table(low_v_f_mind_maxp,11,6,3,low(maxp)).
table(low_v_f_mind_minp,11,6,3,low(minp)).
table(up_v_f_mind_maxp,11,6,3,up(maxp)).
table(up_v_f_mind_minp,11,6,3,up(minp)).
table(low_v_f_mind_maxd,11,6,3,low(maxd)).
table(up_v_f_mind_maxd,11,6,3,up(maxd)).
table(low_v_f_maxd_mind,11,6,3,low(mind)).
table(low_v_f_maxd_maxp,11,6,3,low(maxp)).
table(up_v_f_maxd_mind,11,6,3,up(mind)).
table(up_v_f_maxd_maxp,11,6,3,up(maxp)).
table(low_v_f_maxd_minp,11,6,3,low(minp)).
table(up_v_f_maxd_minp,11,6,3,up(minp)).
table(low_v_f_minp_maxd,11,6,3,low(maxd)).
table(low_v_f_minp_mind,11,6,3,low(mind)).
table(up_v_f_minp_maxd,11,6,3,up(maxd)).
table(up_v_f_minp_mind,11,6,3,up(mind)).
table(low_v_f_minp_maxp,11,6,3,low(maxp)).
table(up_v_f_minp_maxp,11,6,3,up(maxp)).
table(low_v_f_maxp_minp,11,6,3,low(minp)).
table(low_v_f_maxp_maxd,11,6,3,low(maxd)).
table(up_v_f_maxp_minp,11,6,3,up(minp)).
table(up_v_f_maxp_maxd,11,6,3,up(maxd)).
table(low_v_f_maxp_mind,11,6,3,low(mind)).
table(up_v_f_maxp_mind,11,6,3,up(mind)).
table(low_v_maxp,12,6,1,low(maxp)).
table(low_v_minp,12,6,1,low(minp)).
table(up_v_maxp,12,6,1,up(maxp)).
table(up_v_minp,12,6,1,up(minp)).
table(low_v_maxd,12,6,1,low(maxd)).
table(up_v_maxd,12,6,1,up(maxd)).
table(low_v_mind,12,6,1,low(mind)).
table(low_v_f,12,6,1,low(f)).
table(up_v_mind,12,6,1,up(mind)).
table(up_v_f,12,6,1,up(f)).
table(low_v_maxp_f,12,6,2,low(f)).
table(up_v_maxp_f,12,6,2,up(f)).
table(low_v_maxp_mind,12,6,2,low(mind)).
table(low_v_maxp_maxd,12,6,2,low(maxd)).
table(up_v_maxp_mind,12,6,2,up(mind)).
table(up_v_maxp_maxd,12,6,2,up(maxd)).
table(low_v_maxp_minp,12,6,2,low(minp)).
table(up_v_maxp_minp,12,6,2,up(minp)).
table(low_v_minp_maxp,12,6,2,low(maxp)).
table(low_v_minp_f,12,6,2,low(f)).
table(up_v_minp_maxp,12,6,2,up(maxp)).
table(low_v_minp_mind,12,6,2,low(mind)).
table(up_v_minp_f,12,6,2,up(f)).
table(up_v_minp_mind,12,6,2,up(mind)).
table(low_v_minp_maxd,12,6,2,low(maxd)).
table(low_v_maxd_minp,12,6,2,low(minp)).
table(up_v_minp_maxd,12,6,2,up(maxd)).
table(low_v_maxd_maxp,12,6,2,low(maxp)).
table(up_v_maxd_minp,12,6,2,up(minp)).
table(up_v_maxd_maxp,12,6,2,up(maxp)).
table(low_v_maxd_f,12,6,2,low(f)).
table(low_v_maxd_mind,12,6,2,low(mind)).
table(up_v_maxd_f,12,6,2,up(f)).
table(low_v_mind_maxd,12,6,2,low(maxd)).
table(up_v_maxd_mind,12,6,2,up(mind)).
table(up_v_mind_maxd,12,6,2,up(maxd)).
table(low_v_mind_minp,12,6,2,low(minp)).
table(low_v_mind_maxp,12,6,2,low(maxp)).
table(up_v_mind_minp,12,6,2,up(minp)).
table(low_v_mind_f,12,6,2,low(f)).
table(up_v_mind_maxp,12,6,2,up(maxp)).
table(up_v_mind_f,12,6,2,up(f)).
table(low_v_f_mind,12,6,2,low(mind)).
table(low_v_f_maxd,12,6,2,low(maxd)).
table(up_v_f_mind,12,6,2,up(mind)).
table(low_v_f_minp,12,6,2,low(minp)).
table(up_v_f_maxd,12,6,2,up(maxd)).
table(up_v_f_minp,12,6,2,up(minp)).
table(low_v_f_maxp,12,6,2,low(maxp)).
table(low_v_minp_maxp_f,12,6,3,low(f)).
table(up_v_f_maxp,12,6,2,up(maxp)).
table(low_v_minp_maxp_mind,12,6,3,low(mind)).
table(up_v_minp_maxp_f,12,6,3,up(f)).
table(up_v_minp_maxp_mind,12,6,3,up(mind)).
table(low_v_minp_maxp_maxd,12,6,3,low(maxd)).
table(low_v_maxd_minp_maxp,12,6,3,low(maxp)).
table(up_v_minp_maxp_maxd,12,6,3,up(maxd)).
table(low_v_maxd_minp_f,12,6,3,low(f)).
table(up_v_maxd_minp_maxp,12,6,3,up(maxp)).
table(up_v_maxd_minp_f,12,6,3,up(f)).
table(low_v_maxd_minp_mind,12,6,3,low(mind)).
table(low_v_maxd_maxp_minp,12,6,3,low(minp)).
table(up_v_maxd_minp_mind,12,6,3,up(mind)).
table(low_v_maxd_maxp_f,12,6,3,low(f)).
table(up_v_maxd_maxp_minp,12,6,3,up(minp)).
table(up_v_maxd_maxp_f,12,6,3,up(f)).
table(low_v_maxd_maxp_mind,12,6,3,low(mind)).
table(low_v_mind_maxd_maxp,12,6,3,low(maxp)).
table(up_v_maxd_maxp_mind,12,6,3,up(mind)).
table(low_v_mind_maxd_minp,12,6,3,low(minp)).
table(up_v_mind_maxd_maxp,12,6,3,up(maxp)).
table(up_v_mind_maxd_minp,12,6,3,up(minp)).
table(low_v_mind_maxd_f,12,6,3,low(f)).
table(low_v_mind_minp_maxd,12,6,3,low(maxd)).
table(up_v_mind_maxd_f,12,6,3,up(f)).
table(low_v_mind_minp_maxp,12,6,3,low(maxp)).
table(up_v_mind_minp_maxd,12,6,3,up(maxd)).
table(up_v_mind_minp_maxp,12,6,3,up(maxp)).
table(low_v_mind_minp_f,12,6,3,low(f)).
table(low_v_mind_maxp_minp,12,6,3,low(minp)).
table(up_v_mind_minp_f,12,6,3,up(f)).
table(low_v_mind_maxp_maxd,12,6,3,low(maxd)).
table(up_v_mind_maxp_minp,12,6,3,up(minp)).
table(up_v_mind_maxp_maxd,12,6,3,up(maxd)).
table(low_v_mind_maxp_f,12,6,3,low(f)).
table(low_v_f_mind_maxp,12,6,3,low(maxp)).
table(up_v_mind_maxp_f,12,6,3,up(f)).
table(low_v_f_mind_minp,12,6,3,low(minp)).
table(up_v_f_mind_maxp,12,6,3,up(maxp)).
table(up_v_f_mind_minp,12,6,3,up(minp)).
table(low_v_f_mind_maxd,12,6,3,low(maxd)).
table(low_v_f_maxd_mind,12,6,3,low(mind)).
table(low_v_f_maxd_maxp,12,6,3,low(maxp)).
table(up_v_f_mind_maxd,12,6,3,up(maxd)).
table(up_v_f_maxd_mind,12,6,3,up(mind)).
table(up_v_f_maxd_maxp,12,6,3,up(maxp)).
table(low_v_f_maxd_minp,12,6,3,low(minp)).
table(low_v_f_minp_maxd,12,6,3,low(maxd)).
table(up_v_f_maxd_minp,12,6,3,up(minp)).
table(low_v_f_minp_mind,12,6,3,low(mind)).
table(up_v_f_minp_maxd,12,6,3,up(maxd)).
table(up_v_f_minp_mind,12,6,3,up(mind)).
table(low_v_f_minp_maxp,12,6,3,low(maxp)).
table(low_v_f_maxp_minp,12,6,3,low(minp)).
table(up_v_f_minp_maxp,12,6,3,up(maxp)).
table(low_v_f_maxp_maxd,12,6,3,low(maxd)).
table(up_v_f_maxp_minp,12,6,3,up(minp)).
table(up_v_f_maxp_maxd,12,6,3,up(maxd)).
table(low_v_f_maxp_mind,12,6,3,low(mind)).
table(up_v_f_maxp_mind,12,6,3,up(mind)).
table(low_v_maxp,13,6,1,low(maxp)).
table(low_v_minp,13,6,1,low(minp)).
table(up_v_maxp,13,6,1,up(maxp)).
table(low_v_maxd,13,6,1,low(maxd)).
table(up_v_minp,13,6,1,up(minp)).
table(up_v_maxd,13,6,1,up(maxd)).
table(low_v_mind,13,6,1,low(mind)).
table(low_v_f,13,6,1,low(f)).
table(up_v_mind,13,6,1,up(mind)).
table(low_v_maxp_f,13,6,2,low(f)).
table(up_v_f,13,6,1,up(f)).
table(up_v_maxp_f,13,6,2,up(f)).
table(low_v_maxp_mind,13,6,2,low(mind)).
table(low_v_maxp_maxd,13,6,2,low(maxd)).
table(up_v_maxp_mind,13,6,2,up(mind)).
table(low_v_maxp_minp,13,6,2,low(minp)).
table(up_v_maxp_maxd,13,6,2,up(maxd)).
table(up_v_maxp_minp,13,6,2,up(minp)).
table(low_v_minp_maxp,13,6,2,low(maxp)).
table(low_v_minp_f,13,6,2,low(f)).
table(up_v_minp_maxp,13,6,2,up(maxp)).
table(low_v_minp_mind,13,6,2,low(mind)).
table(up_v_minp_f,13,6,2,up(f)).
table(up_v_minp_mind,13,6,2,up(mind)).
table(low_v_minp_maxd,13,6,2,low(maxd)).
table(low_v_maxd_minp,13,6,2,low(minp)).
table(up_v_minp_maxd,13,6,2,up(maxd)).
table(low_v_maxd_maxp,13,6,2,low(maxp)).
table(up_v_maxd_minp,13,6,2,up(minp)).
table(up_v_maxd_maxp,13,6,2,up(maxp)).
table(low_v_maxd_f,13,6,2,low(f)).
table(low_v_maxd_mind,13,6,2,low(mind)).
table(up_v_maxd_f,13,6,2,up(f)).
table(low_v_mind_maxd,13,6,2,low(maxd)).
table(up_v_maxd_mind,13,6,2,up(mind)).
table(up_v_mind_maxd,13,6,2,up(maxd)).
table(low_v_mind_minp,13,6,2,low(minp)).
table(low_v_mind_maxp,13,6,2,low(maxp)).
table(up_v_mind_minp,13,6,2,up(minp)).
table(low_v_mind_f,13,6,2,low(f)).
table(up_v_mind_maxp,13,6,2,up(maxp)).
table(up_v_mind_f,13,6,2,up(f)).
table(low_v_f_mind,13,6,2,low(mind)).
table(low_v_f_maxd,13,6,2,low(maxd)).
table(up_v_f_mind,13,6,2,up(mind)).
table(low_v_f_minp,13,6,2,low(minp)).
table(up_v_f_maxd,13,6,2,up(maxd)).
table(up_v_f_minp,13,6,2,up(minp)).
table(low_v_f_maxp,13,6,2,low(maxp)).
table(low_v_minp_maxp_f,13,6,3,low(f)).
table(up_v_f_maxp,13,6,2,up(maxp)).
table(low_v_minp_maxp_mind,13,6,3,low(mind)).
table(up_v_minp_maxp_f,13,6,3,up(f)).
table(up_v_minp_maxp_mind,13,6,3,up(mind)).
table(low_v_minp_maxp_maxd,13,6,3,low(maxd)).
table(low_v_maxd_minp_maxp,13,6,3,low(maxp)).
table(up_v_minp_maxp_maxd,13,6,3,up(maxd)).
table(low_v_maxd_minp_f,13,6,3,low(f)).
table(up_v_maxd_minp_maxp,13,6,3,up(maxp)).
table(up_v_maxd_minp_f,13,6,3,up(f)).
table(low_v_maxd_minp_mind,13,6,3,low(mind)).
table(low_v_maxd_maxp_minp,13,6,3,low(minp)).
table(up_v_maxd_minp_mind,13,6,3,up(mind)).
table(low_v_maxd_maxp_f,13,6,3,low(f)).
table(up_v_maxd_maxp_minp,13,6,3,up(minp)).
table(up_v_maxd_maxp_f,13,6,3,up(f)).
table(low_v_maxd_maxp_mind,13,6,3,low(mind)).
table(low_v_mind_maxd_maxp,13,6,3,low(maxp)).
table(up_v_maxd_maxp_mind,13,6,3,up(mind)).
table(low_v_mind_maxd_minp,13,6,3,low(minp)).
table(up_v_mind_maxd_maxp,13,6,3,up(maxp)).
table(up_v_mind_maxd_minp,13,6,3,up(minp)).
table(low_v_mind_maxd_f,13,6,3,low(f)).
table(low_v_mind_minp_maxd,13,6,3,low(maxd)).
table(low_v_mind_minp_maxp,13,6,3,low(maxp)).
table(up_v_mind_maxd_f,13,6,3,up(f)).
table(up_v_mind_minp_maxd,13,6,3,up(maxd)).
table(up_v_mind_minp_maxp,13,6,3,up(maxp)).
table(low_v_mind_minp_f,13,6,3,low(f)).
table(low_v_mind_maxp_minp,13,6,3,low(minp)).
table(low_v_mind_maxp_maxd,13,6,3,low(maxd)).
table(up_v_mind_minp_f,13,6,3,up(f)).
table(up_v_mind_maxp_minp,13,6,3,up(minp)).
table(up_v_mind_maxp_maxd,13,6,3,up(maxd)).
table(low_v_mind_maxp_f,13,6,3,low(f)).
table(low_v_f_mind_maxp,13,6,3,low(maxp)).
table(low_v_f_mind_minp,13,6,3,low(minp)).
table(up_v_mind_maxp_f,13,6,3,up(f)).
table(up_v_f_mind_maxp,13,6,3,up(maxp)).
table(up_v_f_mind_minp,13,6,3,up(minp)).
table(low_v_f_mind_maxd,13,6,3,low(maxd)).
table(low_v_f_maxd_mind,13,6,3,low(mind)).
table(low_v_f_maxd_maxp,13,6,3,low(maxp)).
table(up_v_f_mind_maxd,13,6,3,up(maxd)).
table(up_v_f_maxd_mind,13,6,3,up(mind)).
table(up_v_f_maxd_maxp,13,6,3,up(maxp)).
table(low_v_f_maxd_minp,13,6,3,low(minp)).
table(low_v_f_minp_maxd,13,6,3,low(maxd)).
table(low_v_f_minp_mind,13,6,3,low(mind)).
table(up_v_f_maxd_minp,13,6,3,up(minp)).
table(up_v_f_minp_maxd,13,6,3,up(maxd)).
table(up_v_f_minp_mind,13,6,3,up(mind)).
table(low_v_f_minp_maxp,13,6,3,low(maxp)).
table(low_v_f_maxp_minp,13,6,3,low(minp)).
table(up_v_f_minp_maxp,13,6,3,up(maxp)).
table(low_v_f_maxp_maxd,13,6,3,low(maxd)).
table(up_v_f_maxp_minp,13,6,3,up(minp)).
table(up_v_f_maxp_maxd,13,6,3,up(maxd)).
table(low_v_f_maxp_mind,13,6,3,low(mind)).
table(up_v_f_maxp_mind,13,6,3,up(mind)).
table(low_v_maxp,14,6,1,low(maxp)).
table(low_v_minp,14,6,1,low(minp)).
table(low_v_maxd,14,6,1,low(maxd)).
table(up_v_maxp,14,6,1,up(maxp)).
table(up_v_minp,14,6,1,up(minp)).
table(up_v_maxd,14,6,1,up(maxd)).
table(low_v_mind,14,6,1,low(mind)).
table(low_v_f,14,6,1,low(f)).
table(low_v_maxp_f,14,6,2,low(f)).
table(up_v_mind,14,6,1,up(mind)).
table(up_v_f,14,6,1,up(f)).
table(up_v_maxp_f,14,6,2,up(f)).
table(low_v_maxp_mind,14,6,2,low(mind)).
table(low_v_maxp_maxd,14,6,2,low(maxd)).
table(low_v_maxp_minp,14,6,2,low(minp)).
table(up_v_maxp_mind,14,6,2,up(mind)).
table(up_v_maxp_maxd,14,6,2,up(maxd)).
table(up_v_maxp_minp,14,6,2,up(minp)).
table(low_v_minp_maxp,14,6,2,low(maxp)).
table(low_v_minp_f,14,6,2,low(f)).
table(low_v_minp_mind,14,6,2,low(mind)).
table(up_v_minp_maxp,14,6,2,up(maxp)).
table(up_v_minp_f,14,6,2,up(f)).
table(up_v_minp_mind,14,6,2,up(mind)).
table(low_v_minp_maxd,14,6,2,low(maxd)).
table(low_v_maxd_minp,14,6,2,low(minp)).
table(low_v_maxd_maxp,14,6,2,low(maxp)).
table(up_v_minp_maxd,14,6,2,up(maxd)).
table(up_v_maxd_minp,14,6,2,up(minp)).
table(up_v_maxd_maxp,14,6,2,up(maxp)).
table(low_v_maxd_f,14,6,2,low(f)).
table(low_v_maxd_mind,14,6,2,low(mind)).
table(low_v_mind_maxd,14,6,2,low(maxd)).
table(up_v_maxd_f,14,6,2,up(f)).
table(up_v_maxd_mind,14,6,2,up(mind)).
table(up_v_mind_maxd,14,6,2,up(maxd)).
table(low_v_mind_minp,14,6,2,low(minp)).
table(low_v_mind_maxp,14,6,2,low(maxp)).
table(low_v_mind_f,14,6,2,low(f)).
table(up_v_mind_minp,14,6,2,up(minp)).
table(up_v_mind_maxp,14,6,2,up(maxp)).
table(up_v_mind_f,14,6,2,up(f)).
table(low_v_f_mind,14,6,2,low(mind)).
table(low_v_f_maxd,14,6,2,low(maxd)).
table(low_v_f_minp,14,6,2,low(minp)).
table(up_v_f_mind,14,6,2,up(mind)).
table(up_v_f_maxd,14,6,2,up(maxd)).
table(up_v_f_minp,14,6,2,up(minp)).
table(low_v_f_maxp,14,6,2,low(maxp)).
table(low_v_minp_maxp_f,14,6,3,low(f)).
table(low_v_minp_maxp_mind,14,6,3,low(mind)).
table(up_v_f_maxp,14,6,2,up(maxp)).
table(up_v_minp_maxp_f,14,6,3,up(f)).
table(up_v_minp_maxp_mind,14,6,3,up(mind)).
table(low_v_minp_maxp_maxd,14,6,3,low(maxd)).
table(low_v_maxd_minp_maxp,14,6,3,low(maxp)).
table(low_v_maxd_minp_f,14,6,3,low(f)).
table(up_v_minp_maxp_maxd,14,6,3,up(maxd)).
table(up_v_maxd_minp_maxp,14,6,3,up(maxp)).
table(up_v_maxd_minp_f,14,6,3,up(f)).
table(low_v_maxd_minp_mind,14,6,3,low(mind)).
table(low_v_maxd_maxp_minp,14,6,3,low(minp)).
table(low_v_maxd_maxp_f,14,6,3,low(f)).
table(up_v_maxd_minp_mind,14,6,3,up(mind)).
table(up_v_maxd_maxp_minp,14,6,3,up(minp)).
table(up_v_maxd_maxp_f,14,6,3,up(f)).
table(low_v_maxd_maxp_mind,14,6,3,low(mind)).
table(low_v_mind_maxd_maxp,14,6,3,low(maxp)).
table(low_v_mind_maxd_minp,14,6,3,low(minp)).
table(up_v_maxd_maxp_mind,14,6,3,up(mind)).
table(up_v_mind_maxd_maxp,14,6,3,up(maxp)).
table(up_v_mind_maxd_minp,14,6,3,up(minp)).
table(low_v_mind_maxd_f,14,6,3,low(f)).
table(low_v_mind_minp_maxd,14,6,3,low(maxd)).
table(low_v_mind_minp_maxp,14,6,3,low(maxp)).
table(up_v_mind_maxd_f,14,6,3,up(f)).
table(up_v_mind_minp_maxd,14,6,3,up(maxd)).
table(up_v_mind_minp_maxp,14,6,3,up(maxp)).
table(low_v_mind_minp_f,14,6,3,low(f)).
table(low_v_mind_maxp_minp,14,6,3,low(minp)).
table(low_v_mind_maxp_maxd,14,6,3,low(maxd)).
table(up_v_mind_minp_f,14,6,3,up(f)).
table(up_v_mind_maxp_minp,14,6,3,up(minp)).
table(up_v_mind_maxp_maxd,14,6,3,up(maxd)).
table(low_v_mind_maxp_f,14,6,3,low(f)).
table(low_v_f_mind_maxp,14,6,3,low(maxp)).
table(low_v_f_mind_minp,14,6,3,low(minp)).
table(up_v_mind_maxp_f,14,6,3,up(f)).
table(up_v_f_mind_maxp,14,6,3,up(maxp)).
table(up_v_f_mind_minp,14,6,3,up(minp)).
table(low_v_f_mind_maxd,14,6,3,low(maxd)).
table(low_v_f_maxd_mind,14,6,3,low(mind)).
table(low_v_f_maxd_maxp,14,6,3,low(maxp)).
table(up_v_f_mind_maxd,14,6,3,up(maxd)).
table(up_v_f_maxd_mind,14,6,3,up(mind)).
table(up_v_f_maxd_maxp,14,6,3,up(maxp)).
table(low_v_f_maxd_minp,14,6,3,low(minp)).
table(low_v_f_minp_maxd,14,6,3,low(maxd)).
table(low_v_f_minp_mind,14,6,3,low(mind)).
table(up_v_f_maxd_minp,14,6,3,up(minp)).
table(up_v_f_minp_maxd,14,6,3,up(maxd)).
table(up_v_f_minp_mind,14,6,3,up(mind)).
table(low_v_f_minp_maxp,14,6,3,low(maxp)).
table(low_v_f_maxp_minp,14,6,3,low(minp)).
table(low_v_f_maxp_maxd,14,6,3,low(maxd)).
table(up_v_f_minp_maxp,14,6,3,up(maxp)).
table(up_v_f_maxp_minp,14,6,3,up(minp)).
table(up_v_f_maxp_maxd,14,6,3,up(maxd)).
table(low_v_f_maxp_mind,14,6,3,low(mind)).
table(up_v_f_maxp_mind,14,6,3,up(mind)).
table(low_v_maxp,15,6,1,low(maxp)).
table(low_v_minp,15,6,1,low(minp)).
table(low_v_maxd,15,6,1,low(maxd)).
table(up_v_maxp,15,6,1,up(maxp)).
table(up_v_minp,15,6,1,up(minp)).
table(up_v_maxd,15,6,1,up(maxd)).
table(low_v_mind,15,6,1,low(mind)).
table(low_v_f,15,6,1,low(f)).
table(low_v_maxp_f,15,6,2,low(f)).
table(up_v_mind,15,6,1,up(mind)).
table(up_v_f,15,6,1,up(f)).
table(up_v_maxp_f,15,6,2,up(f)).
table(low_v_maxp_mind,15,6,2,low(mind)).
table(low_v_maxp_maxd,15,6,2,low(maxd)).
table(low_v_maxp_minp,15,6,2,low(minp)).
table(up_v_maxp_mind,15,6,2,up(mind)).
table(up_v_maxp_maxd,15,6,2,up(maxd)).
table(up_v_maxp_minp,15,6,2,up(minp)).
table(low_v_minp_maxp,15,6,2,low(maxp)).
table(low_v_minp_f,15,6,2,low(f)).
table(low_v_minp_mind,15,6,2,low(mind)).
table(up_v_minp_maxp,15,6,2,up(maxp)).
table(up_v_minp_f,15,6,2,up(f)).
table(up_v_minp_mind,15,6,2,up(mind)).
table(low_v_minp_maxd,15,6,2,low(maxd)).
table(low_v_maxd_minp,15,6,2,low(minp)).
table(low_v_maxd_maxp,15,6,2,low(maxp)).
table(up_v_minp_maxd,15,6,2,up(maxd)).
table(up_v_maxd_minp,15,6,2,up(minp)).
table(up_v_maxd_maxp,15,6,2,up(maxp)).
table(low_v_maxd_f,15,6,2,low(f)).
table(low_v_maxd_mind,15,6,2,low(mind)).
table(low_v_mind_maxd,15,6,2,low(maxd)).
table(up_v_maxd_f,15,6,2,up(f)).
table(up_v_maxd_mind,15,6,2,up(mind)).
table(up_v_mind_maxd,15,6,2,up(maxd)).
table(low_v_mind_minp,15,6,2,low(minp)).
table(low_v_mind_maxp,15,6,2,low(maxp)).
table(low_v_mind_f,15,6,2,low(f)).
table(up_v_mind_minp,15,6,2,up(minp)).
table(up_v_mind_maxp,15,6,2,up(maxp)).
table(up_v_mind_f,15,6,2,up(f)).
table(low_v_f_mind,15,6,2,low(mind)).
table(low_v_f_maxd,15,6,2,low(maxd)).
table(low_v_f_minp,15,6,2,low(minp)).
table(up_v_f_mind,15,6,2,up(mind)).
table(up_v_f_maxd,15,6,2,up(maxd)).
table(up_v_f_minp,15,6,2,up(minp)).
table(low_v_f_maxp,15,6,2,low(maxp)).
table(low_v_minp_maxp_f,15,6,3,low(f)).
table(low_v_minp_maxp_mind,15,6,3,low(mind)).
table(up_v_f_maxp,15,6,2,up(maxp)).
table(up_v_minp_maxp_f,15,6,3,up(f)).
table(up_v_minp_maxp_mind,15,6,3,up(mind)).
table(low_v_minp_maxp_maxd,15,6,3,low(maxd)).
table(low_v_maxd_minp_maxp,15,6,3,low(maxp)).
table(low_v_maxd_minp_f,15,6,3,low(f)).
table(up_v_minp_maxp_maxd,15,6,3,up(maxd)).
table(up_v_maxd_minp_maxp,15,6,3,up(maxp)).
table(up_v_maxd_minp_f,15,6,3,up(f)).
table(low_v_maxd_minp_mind,15,6,3,low(mind)).
table(low_v_maxd_maxp_minp,15,6,3,low(minp)).
table(low_v_maxd_maxp_f,15,6,3,low(f)).
table(up_v_maxd_minp_mind,15,6,3,up(mind)).
table(up_v_maxd_maxp_minp,15,6,3,up(minp)).
table(up_v_maxd_maxp_f,15,6,3,up(f)).
table(low_v_maxd_maxp_mind,15,6,3,low(mind)).
table(low_v_mind_maxd_maxp,15,6,3,low(maxp)).
table(low_v_mind_maxd_minp,15,6,3,low(minp)).
table(up_v_maxd_maxp_mind,15,6,3,up(mind)).
table(up_v_mind_maxd_maxp,15,6,3,up(maxp)).
table(up_v_mind_maxd_minp,15,6,3,up(minp)).
table(low_v_mind_maxd_f,15,6,3,low(f)).
table(low_v_mind_minp_maxd,15,6,3,low(maxd)).
table(low_v_mind_minp_maxp,15,6,3,low(maxp)).
table(up_v_mind_maxd_f,15,6,3,up(f)).
table(up_v_mind_minp_maxd,15,6,3,up(maxd)).
table(up_v_mind_minp_maxp,15,6,3,up(maxp)).
table(low_v_mind_minp_f,15,6,3,low(f)).
table(low_v_mind_maxp_minp,15,6,3,low(minp)).
table(low_v_mind_maxp_maxd,15,6,3,low(maxd)).
table(up_v_mind_minp_f,15,6,3,up(f)).
table(up_v_mind_maxp_minp,15,6,3,up(minp)).
table(up_v_mind_maxp_maxd,15,6,3,up(maxd)).
table(low_v_mind_maxp_f,15,6,3,low(f)).
table(low_v_f_mind_maxp,15,6,3,low(maxp)).
table(low_v_f_mind_minp,15,6,3,low(minp)).
table(up_v_mind_maxp_f,15,6,3,up(f)).
table(up_v_f_mind_maxp,15,6,3,up(maxp)).
table(up_v_f_mind_minp,15,6,3,up(minp)).
table(low_v_f_mind_maxd,15,6,3,low(maxd)).
table(low_v_f_maxd_mind,15,6,3,low(mind)).
table(low_v_f_maxd_maxp,15,6,3,low(maxp)).
table(up_v_f_mind_maxd,15,6,3,up(maxd)).
table(up_v_f_maxd_mind,15,6,3,up(mind)).
table(up_v_f_maxd_maxp,15,6,3,up(maxp)).
table(low_v_f_maxd_minp,15,6,3,low(minp)).
table(low_v_f_minp_maxd,15,6,3,low(maxd)).
table(low_v_f_minp_mind,15,6,3,low(mind)).
table(up_v_f_maxd_minp,15,6,3,up(minp)).
table(up_v_f_minp_maxd,15,6,3,up(maxd)).
table(up_v_f_minp_mind,15,6,3,up(mind)).
table(low_v_f_minp_maxp,15,6,3,low(maxp)).
table(low_v_f_maxp_minp,15,6,3,low(minp)).
table(low_v_f_maxp_maxd,15,6,3,low(maxd)).
table(up_v_f_minp_maxp,15,6,3,up(maxp)).
table(up_v_f_maxp_minp,15,6,3,up(minp)).
table(up_v_f_maxp_maxd,15,6,3,up(maxd)).
table(low_v_f_maxp_mind,15,6,3,low(mind)).
table(up_v_f_maxp_mind,15,6,3,up(mind)).
table(low_v_maxp,16,6,1,low(maxp)).
table(low_v_minp,16,6,1,low(minp)).
table(low_v_maxd,16,6,1,low(maxd)).
table(up_v_maxp,16,6,1,up(maxp)).
table(up_v_minp,16,6,1,up(minp)).
table(up_v_maxd,16,6,1,up(maxd)).
table(low_v_mind,16,6,1,low(mind)).
table(low_v_f,16,6,1,low(f)).
table(low_v_maxp_f,16,6,2,low(f)).
table(up_v_mind,16,6,1,up(mind)).
table(up_v_f,16,6,1,up(f)).
table(up_v_maxp_f,16,6,2,up(f)).
table(low_v_maxp_mind,16,6,2,low(mind)).
table(low_v_maxp_maxd,16,6,2,low(maxd)).
table(low_v_maxp_minp,16,6,2,low(minp)).
table(up_v_maxp_mind,16,6,2,up(mind)).
table(up_v_maxp_maxd,16,6,2,up(maxd)).
table(up_v_maxp_minp,16,6,2,up(minp)).
table(low_v_minp_maxp,16,6,2,low(maxp)).
table(low_v_minp_f,16,6,2,low(f)).
table(low_v_minp_mind,16,6,2,low(mind)).
table(up_v_minp_maxp,16,6,2,up(maxp)).
table(up_v_minp_f,16,6,2,up(f)).
table(up_v_minp_mind,16,6,2,up(mind)).
table(low_v_minp_maxd,16,6,2,low(maxd)).
table(low_v_maxd_minp,16,6,2,low(minp)).
table(low_v_maxd_maxp,16,6,2,low(maxp)).
table(up_v_minp_maxd,16,6,2,up(maxd)).
table(up_v_maxd_minp,16,6,2,up(minp)).
table(up_v_maxd_maxp,16,6,2,up(maxp)).
table(low_v_maxd_f,16,6,2,low(f)).
table(low_v_maxd_mind,16,6,2,low(mind)).
table(low_v_mind_maxd,16,6,2,low(maxd)).
table(up_v_maxd_f,16,6,2,up(f)).
table(up_v_maxd_mind,16,6,2,up(mind)).
table(up_v_mind_maxd,16,6,2,up(maxd)).
table(low_v_mind_minp,16,6,2,low(minp)).
table(low_v_mind_maxp,16,6,2,low(maxp)).
table(low_v_mind_f,16,6,2,low(f)).
table(up_v_mind_minp,16,6,2,up(minp)).
table(up_v_mind_maxp,16,6,2,up(maxp)).
table(up_v_mind_f,16,6,2,up(f)).
table(low_v_f_mind,16,6,2,low(mind)).
table(low_v_f_maxd,16,6,2,low(maxd)).
table(low_v_f_minp,16,6,2,low(minp)).
table(up_v_f_mind,16,6,2,up(mind)).
table(up_v_f_maxd,16,6,2,up(maxd)).
table(up_v_f_minp,16,6,2,up(minp)).
table(low_v_f_maxp,16,6,2,low(maxp)).
table(low_v_minp_maxp_f,16,6,3,low(f)).
table(low_v_minp_maxp_mind,16,6,3,low(mind)).
table(up_v_f_maxp,16,6,2,up(maxp)).
table(up_v_minp_maxp_f,16,6,3,up(f)).
table(up_v_minp_maxp_mind,16,6,3,up(mind)).
table(low_v_minp_maxp_maxd,16,6,3,low(maxd)).
table(low_v_maxd_minp_maxp,16,6,3,low(maxp)).
table(low_v_maxd_minp_f,16,6,3,low(f)).
table(up_v_minp_maxp_maxd,16,6,3,up(maxd)).
table(up_v_maxd_minp_maxp,16,6,3,up(maxp)).
table(up_v_maxd_minp_f,16,6,3,up(f)).
table(low_v_maxd_minp_mind,16,6,3,low(mind)).
table(low_v_maxd_maxp_minp,16,6,3,low(minp)).
table(low_v_maxd_maxp_f,16,6,3,low(f)).
table(up_v_maxd_minp_mind,16,6,3,up(mind)).
table(up_v_maxd_maxp_minp,16,6,3,up(minp)).
table(up_v_maxd_maxp_f,16,6,3,up(f)).
table(low_v_maxd_maxp_mind,16,6,3,low(mind)).
table(low_v_mind_maxd_maxp,16,6,3,low(maxp)).
table(low_v_mind_maxd_minp,16,6,3,low(minp)).
table(up_v_maxd_maxp_mind,16,6,3,up(mind)).
table(up_v_mind_maxd_maxp,16,6,3,up(maxp)).
table(up_v_mind_maxd_minp,16,6,3,up(minp)).
table(low_v_mind_maxd_f,16,6,3,low(f)).
table(low_v_mind_minp_maxd,16,6,3,low(maxd)).
table(low_v_mind_minp_maxp,16,6,3,low(maxp)).
table(up_v_mind_maxd_f,16,6,3,up(f)).
table(up_v_mind_minp_maxd,16,6,3,up(maxd)).
table(up_v_mind_minp_maxp,16,6,3,up(maxp)).
table(low_v_mind_minp_f,16,6,3,low(f)).
table(low_v_mind_maxp_minp,16,6,3,low(minp)).
table(low_v_mind_maxp_maxd,16,6,3,low(maxd)).
table(up_v_mind_minp_f,16,6,3,up(f)).
table(up_v_mind_maxp_minp,16,6,3,up(minp)).
table(up_v_mind_maxp_maxd,16,6,3,up(maxd)).
table(low_v_mind_maxp_f,16,6,3,low(f)).
table(low_v_f_mind_maxp,16,6,3,low(maxp)).
table(low_v_f_mind_minp,16,6,3,low(minp)).
table(up_v_mind_maxp_f,16,6,3,up(f)).
table(up_v_f_mind_maxp,16,6,3,up(maxp)).
table(up_v_f_mind_minp,16,6,3,up(minp)).
table(low_v_f_mind_maxd,16,6,3,low(maxd)).
table(low_v_f_maxd_mind,16,6,3,low(mind)).
table(low_v_f_maxd_maxp,16,6,3,low(maxp)).
table(up_v_f_mind_maxd,16,6,3,up(maxd)).
table(up_v_f_maxd_mind,16,6,3,up(mind)).
table(up_v_f_maxd_maxp,16,6,3,up(maxp)).
table(low_v_f_minp_maxd,16,6,3,low(maxd)).
table(low_v_f_maxd_minp,16,6,3,low(minp)).
table(low_v_f_minp_mind,16,6,3,low(mind)).
table(up_v_f_minp_maxd,16,6,3,up(maxd)).
table(up_v_f_maxd_minp,16,6,3,up(minp)).
table(up_v_f_minp_mind,16,6,3,up(mind)).
table(low_v_f_minp_maxp,16,6,3,low(maxp)).
table(low_v_f_maxp_minp,16,6,3,low(minp)).
table(low_v_f_maxp_maxd,16,6,3,low(maxd)).
table(up_v_f_minp_maxp,16,6,3,up(maxp)).
table(up_v_f_maxp_minp,16,6,3,up(minp)).
table(up_v_f_maxp_maxd,16,6,3,up(maxd)).
table(low_v_f_maxp_mind,16,6,3,low(mind)).
table(up_v_f_maxp_mind,16,6,3,up(mind)).
table(low_v_maxp,17,6,1,low(maxp)).
table(low_v_minp,17,6,1,low(minp)).
table(low_v_maxd,17,6,1,low(maxd)).
table(up_v_maxp,17,6,1,up(maxp)).
table(up_v_minp,17,6,1,up(minp)).
table(up_v_maxd,17,6,1,up(maxd)).
table(low_v_mind,17,6,1,low(mind)).
table(low_v_f,17,6,1,low(f)).
table(low_v_maxp_f,17,6,2,low(f)).
table(up_v_mind,17,6,1,up(mind)).
table(up_v_f,17,6,1,up(f)).
table(up_v_maxp_f,17,6,2,up(f)).
table(low_v_maxp_mind,17,6,2,low(mind)).
table(low_v_maxp_maxd,17,6,2,low(maxd)).
table(low_v_maxp_minp,17,6,2,low(minp)).
table(up_v_maxp_mind,17,6,2,up(mind)).
table(up_v_maxp_maxd,17,6,2,up(maxd)).
table(up_v_maxp_minp,17,6,2,up(minp)).
table(low_v_minp_maxp,17,6,2,low(maxp)).
table(low_v_minp_f,17,6,2,low(f)).
table(low_v_minp_mind,17,6,2,low(mind)).
table(up_v_minp_maxp,17,6,2,up(maxp)).
table(up_v_minp_f,17,6,2,up(f)).
table(up_v_minp_mind,17,6,2,up(mind)).
table(low_v_minp_maxd,17,6,2,low(maxd)).
table(low_v_maxd_minp,17,6,2,low(minp)).
table(low_v_maxd_maxp,17,6,2,low(maxp)).
table(up_v_minp_maxd,17,6,2,up(maxd)).
table(up_v_maxd_minp,17,6,2,up(minp)).
table(up_v_maxd_maxp,17,6,2,up(maxp)).
table(low_v_maxd_f,17,6,2,low(f)).
table(low_v_maxd_mind,17,6,2,low(mind)).
table(low_v_mind_maxd,17,6,2,low(maxd)).
table(up_v_maxd_f,17,6,2,up(f)).
table(up_v_maxd_mind,17,6,2,up(mind)).
table(up_v_mind_maxd,17,6,2,up(maxd)).
table(low_v_mind_minp,17,6,2,low(minp)).
table(low_v_mind_maxp,17,6,2,low(maxp)).
table(low_v_mind_f,17,6,2,low(f)).
table(up_v_mind_minp,17,6,2,up(minp)).
table(up_v_mind_maxp,17,6,2,up(maxp)).
table(up_v_mind_f,17,6,2,up(f)).
table(low_v_f_mind,17,6,2,low(mind)).
table(low_v_f_maxd,17,6,2,low(maxd)).
table(low_v_f_minp,17,6,2,low(minp)).
table(up_v_f_mind,17,6,2,up(mind)).
table(up_v_f_maxd,17,6,2,up(maxd)).
table(up_v_f_minp,17,6,2,up(minp)).
table(low_v_f_maxp,17,6,2,low(maxp)).
table(low_v_minp_maxp_f,17,6,3,low(f)).
table(low_v_minp_maxp_mind,17,6,3,low(mind)).
table(up_v_f_maxp,17,6,2,up(maxp)).
table(up_v_minp_maxp_f,17,6,3,up(f)).
table(up_v_minp_maxp_mind,17,6,3,up(mind)).
table(low_v_minp_maxp_maxd,17,6,3,low(maxd)).
table(low_v_maxd_minp_maxp,17,6,3,low(maxp)).
table(low_v_maxd_minp_f,17,6,3,low(f)).
table(up_v_minp_maxp_maxd,17,6,3,up(maxd)).
table(up_v_maxd_minp_maxp,17,6,3,up(maxp)).
table(up_v_maxd_minp_f,17,6,3,up(f)).
table(low_v_maxd_minp_mind,17,6,3,low(mind)).
table(low_v_maxd_maxp_minp,17,6,3,low(minp)).
table(low_v_maxd_maxp_f,17,6,3,low(f)).
table(up_v_maxd_minp_mind,17,6,3,up(mind)).
table(up_v_maxd_maxp_minp,17,6,3,up(minp)).
table(up_v_maxd_maxp_f,17,6,3,up(f)).
table(low_v_maxd_maxp_mind,17,6,3,low(mind)).
table(low_v_mind_maxd_maxp,17,6,3,low(maxp)).
table(low_v_mind_maxd_minp,17,6,3,low(minp)).
table(up_v_maxd_maxp_mind,17,6,3,up(mind)).
table(up_v_mind_maxd_maxp,17,6,3,up(maxp)).
table(up_v_mind_maxd_minp,17,6,3,up(minp)).
table(low_v_mind_maxd_f,17,6,3,low(f)).
table(low_v_mind_minp_maxd,17,6,3,low(maxd)).
table(low_v_mind_minp_maxp,17,6,3,low(maxp)).
table(up_v_mind_maxd_f,17,6,3,up(f)).
table(up_v_mind_minp_maxd,17,6,3,up(maxd)).
table(up_v_mind_minp_maxp,17,6,3,up(maxp)).
table(low_v_mind_minp_f,17,6,3,low(f)).
table(low_v_mind_maxp_minp,17,6,3,low(minp)).
table(low_v_mind_maxp_maxd,17,6,3,low(maxd)).
table(up_v_mind_minp_f,17,6,3,up(f)).
table(up_v_mind_maxp_minp,17,6,3,up(minp)).
table(up_v_mind_maxp_maxd,17,6,3,up(maxd)).
table(low_v_mind_maxp_f,17,6,3,low(f)).
table(low_v_f_mind_maxp,17,6,3,low(maxp)).
table(low_v_f_mind_minp,17,6,3,low(minp)).
table(up_v_mind_maxp_f,17,6,3,up(f)).
table(up_v_f_mind_maxp,17,6,3,up(maxp)).
table(up_v_f_mind_minp,17,6,3,up(minp)).
table(low_v_f_mind_maxd,17,6,3,low(maxd)).
table(low_v_f_maxd_mind,17,6,3,low(mind)).
table(low_v_f_maxd_maxp,17,6,3,low(maxp)).
table(up_v_f_mind_maxd,17,6,3,up(maxd)).
table(up_v_f_maxd_mind,17,6,3,up(mind)).
table(up_v_f_maxd_maxp,17,6,3,up(maxp)).
table(low_v_f_maxd_minp,17,6,3,low(minp)).
table(low_v_f_minp_maxd,17,6,3,low(maxd)).
table(low_v_f_minp_mind,17,6,3,low(mind)).
table(up_v_f_maxd_minp,17,6,3,up(minp)).
table(up_v_f_minp_maxd,17,6,3,up(maxd)).
table(up_v_f_minp_mind,17,6,3,up(mind)).
table(low_v_f_minp_maxp,17,6,3,low(maxp)).
table(low_v_f_maxp_minp,17,6,3,low(minp)).
table(low_v_f_maxp_maxd,17,6,3,low(maxd)).
table(up_v_f_minp_maxp,17,6,3,up(maxp)).
table(up_v_f_maxp_minp,17,6,3,up(minp)).
table(up_v_f_maxp_maxd,17,6,3,up(maxd)).
table(low_v_f_maxp_mind,17,6,3,low(mind)).
table(up_v_f_maxp_mind,17,6,3,up(mind)).
table(low_v_maxp,18,6,1,low(maxp)).
table(low_v_minp,18,6,1,low(minp)).
table(low_v_maxd,18,6,1,low(maxd)).
table(up_v_maxp,18,6,1,up(maxp)).
table(up_v_minp,18,6,1,up(minp)).
table(up_v_maxd,18,6,1,up(maxd)).
table(low_v_mind,18,6,1,low(mind)).
table(low_v_f,18,6,1,low(f)).
table(low_v_maxp_f,18,6,2,low(f)).
table(up_v_mind,18,6,1,up(mind)).
table(up_v_f,18,6,1,up(f)).
table(up_v_maxp_f,18,6,2,up(f)).
table(low_v_maxp_mind,18,6,2,low(mind)).
table(low_v_maxp_maxd,18,6,2,low(maxd)).
table(low_v_maxp_minp,18,6,2,low(minp)).
table(up_v_maxp_mind,18,6,2,up(mind)).
table(up_v_maxp_maxd,18,6,2,up(maxd)).
table(up_v_maxp_minp,18,6,2,up(minp)).
table(low_v_minp_maxp,18,6,2,low(maxp)).
table(low_v_minp_f,18,6,2,low(f)).
table(low_v_minp_mind,18,6,2,low(mind)).
table(up_v_minp_maxp,18,6,2,up(maxp)).
table(up_v_minp_f,18,6,2,up(f)).
table(up_v_minp_mind,18,6,2,up(mind)).
table(low_v_minp_maxd,18,6,2,low(maxd)).
table(low_v_maxd_minp,18,6,2,low(minp)).
table(low_v_maxd_maxp,18,6,2,low(maxp)).
table(up_v_minp_maxd,18,6,2,up(maxd)).
table(up_v_maxd_minp,18,6,2,up(minp)).
table(up_v_maxd_maxp,18,6,2,up(maxp)).
table(low_v_maxd_f,18,6,2,low(f)).
table(low_v_maxd_mind,18,6,2,low(mind)).
table(low_v_mind_maxd,18,6,2,low(maxd)).
table(up_v_maxd_f,18,6,2,up(f)).
table(up_v_maxd_mind,18,6,2,up(mind)).
table(up_v_mind_maxd,18,6,2,up(maxd)).
table(low_v_mind_minp,18,6,2,low(minp)).
table(low_v_mind_maxp,18,6,2,low(maxp)).
table(low_v_mind_f,18,6,2,low(f)).
table(up_v_mind_minp,18,6,2,up(minp)).
table(up_v_mind_maxp,18,6,2,up(maxp)).
table(up_v_mind_f,18,6,2,up(f)).
table(low_v_f_mind,18,6,2,low(mind)).
table(low_v_f_maxd,18,6,2,low(maxd)).
table(low_v_f_minp,18,6,2,low(minp)).
table(up_v_f_mind,18,6,2,up(mind)).
table(up_v_f_maxd,18,6,2,up(maxd)).
table(up_v_f_minp,18,6,2,up(minp)).
table(low_v_f_maxp,18,6,2,low(maxp)).
table(low_v_minp_maxp_f,18,6,3,low(f)).
table(low_v_minp_maxp_mind,18,6,3,low(mind)).
table(up_v_f_maxp,18,6,2,up(maxp)).
table(up_v_minp_maxp_f,18,6,3,up(f)).
table(up_v_minp_maxp_mind,18,6,3,up(mind)).
table(low_v_minp_maxp_maxd,18,6,3,low(maxd)).
table(low_v_maxd_minp_maxp,18,6,3,low(maxp)).
table(low_v_maxd_minp_f,18,6,3,low(f)).
table(up_v_minp_maxp_maxd,18,6,3,up(maxd)).
table(up_v_maxd_minp_maxp,18,6,3,up(maxp)).
table(up_v_maxd_minp_f,18,6,3,up(f)).
table(low_v_maxd_minp_mind,18,6,3,low(mind)).
table(low_v_maxd_maxp_minp,18,6,3,low(minp)).
table(low_v_maxd_maxp_f,18,6,3,low(f)).
table(up_v_maxd_minp_mind,18,6,3,up(mind)).
table(up_v_maxd_maxp_minp,18,6,3,up(minp)).
table(up_v_maxd_maxp_f,18,6,3,up(f)).
table(low_v_maxd_maxp_mind,18,6,3,low(mind)).
table(low_v_mind_maxd_maxp,18,6,3,low(maxp)).
table(low_v_mind_maxd_minp,18,6,3,low(minp)).
table(up_v_maxd_maxp_mind,18,6,3,up(mind)).
table(up_v_mind_maxd_maxp,18,6,3,up(maxp)).
table(up_v_mind_maxd_minp,18,6,3,up(minp)).
table(low_v_mind_maxd_f,18,6,3,low(f)).
table(low_v_mind_minp_maxd,18,6,3,low(maxd)).
table(low_v_mind_minp_maxp,18,6,3,low(maxp)).
table(up_v_mind_maxd_f,18,6,3,up(f)).
table(up_v_mind_minp_maxd,18,6,3,up(maxd)).
table(up_v_mind_minp_maxp,18,6,3,up(maxp)).
table(low_v_mind_minp_f,18,6,3,low(f)).
table(low_v_mind_maxp_minp,18,6,3,low(minp)).
table(low_v_mind_maxp_maxd,18,6,3,low(maxd)).
table(up_v_mind_minp_f,18,6,3,up(f)).
table(up_v_mind_maxp_minp,18,6,3,up(minp)).
table(up_v_mind_maxp_maxd,18,6,3,up(maxd)).
table(low_v_mind_maxp_f,18,6,3,low(f)).
table(low_v_f_mind_maxp,18,6,3,low(maxp)).
table(low_v_f_mind_minp,18,6,3,low(minp)).
table(up_v_mind_maxp_f,18,6,3,up(f)).
table(up_v_f_mind_maxp,18,6,3,up(maxp)).
table(up_v_f_mind_minp,18,6,3,up(minp)).
table(low_v_f_mind_maxd,18,6,3,low(maxd)).
table(low_v_f_maxd_mind,18,6,3,low(mind)).
table(low_v_f_maxd_maxp,18,6,3,low(maxp)).
table(up_v_f_mind_maxd,18,6,3,up(maxd)).
table(up_v_f_maxd_mind,18,6,3,up(mind)).
table(up_v_f_maxd_maxp,18,6,3,up(maxp)).
table(low_v_f_maxd_minp,18,6,3,low(minp)).
table(low_v_f_minp_maxd,18,6,3,low(maxd)).
table(low_v_f_minp_mind,18,6,3,low(mind)).
table(up_v_f_maxd_minp,18,6,3,up(minp)).
table(up_v_f_minp_maxd,18,6,3,up(maxd)).
table(up_v_f_minp_mind,18,6,3,up(mind)).
table(low_v_f_minp_maxp,18,6,3,low(maxp)).
table(low_v_f_maxp_minp,18,6,3,low(minp)).
table(low_v_f_maxp_maxd,18,6,3,low(maxd)).
table(up_v_f_minp_maxp,18,6,3,up(maxp)).
table(up_v_f_maxp_minp,18,6,3,up(minp)).
table(up_v_f_maxp_maxd,18,6,3,up(maxd)).
table(low_v_f_maxp_mind,18,6,3,low(mind)).
table(up_v_f_maxp_mind,18,6,3,up(mind)).
table(low_v_f_maxp,3,6,2,low(maxp)).
table(low_v_f_minp,3,6,2,low(minp)).
table(low_v_minp_maxp_f,3,6,3,low(f)).
table(up_v_f_maxp,3,6,2,up(maxp)).
table(up_v_f_minp,3,6,2,up(minp)).
table(up_v_minp_maxp_f,3,6,3,up(f)).
table(low_v_f_maxd,3,6,2,low(maxd)).
table(up_v_f_maxd,3,6,2,up(maxd)).
table(low_v_minp_maxp_maxd,3,6,3,low(maxd)).
table(up_v_minp_maxp_maxd,3,6,3,up(maxd)).
table(low_v_minp_maxp_mind,3,6,3,low(mind)).
table(up_v_minp_maxp_mind,3,6,3,up(mind)).
table(low_v_maxd_minp_maxp,3,6,3,low(maxp)).
table(low_v_maxd_minp_f,3,6,3,low(f)).
table(up_v_maxd_minp_maxp,3,6,3,up(maxp)).
table(up_v_maxd_minp_f,3,6,3,up(f)).
table(low_v_maxd_maxp_mind,3,6,3,low(mind)).
table(up_v_maxd_maxp_mind,3,6,3,up(mind)).
table(low_v_maxd_minp_mind,3,6,3,low(mind)).
table(up_v_maxd_minp_mind,3,6,3,up(mind)).
table(low_v_maxd_maxp_minp,3,6,3,low(minp)).
table(up_v_maxd_maxp_minp,3,6,3,up(minp)).
table(low_v_maxd_maxp_f,3,6,3,low(f)).
table(up_v_maxd_maxp_f,3,6,3,up(f)).
table(low_v_mind_maxd_maxp,3,6,3,low(maxp)).
table(up_v_mind_maxd_maxp,3,6,3,up(maxp)).
table(low_v_mind_maxd_minp,3,6,3,low(minp)).
table(up_v_mind_maxd_minp,3,6,3,up(minp)).
table(low_v_mind_maxd_f,3,6,3,low(f)).
table(low_v_mind_minp_maxd,3,6,3,low(maxd)).
table(up_v_mind_maxd_f,3,6,3,up(f)).
table(up_v_mind_minp_maxd,3,6,3,up(maxd)).
table(low_v_mind_minp_maxp,3,6,3,low(maxp)).
table(up_v_mind_minp_maxp,3,6,3,up(maxp)).
table(low_v_mind_minp_f,3,6,3,low(f)).
table(up_v_mind_minp_f,3,6,3,up(f)).
table(low_v_mind_maxp_minp,3,6,3,low(minp)).
table(up_v_mind_maxp_minp,3,6,3,up(minp)).
table(low_v_mind_maxp_maxd,3,6,3,low(maxd)).
table(up_v_mind_maxp_maxd,3,6,3,up(maxd)).
table(low_v_mind_maxp_f,3,6,3,low(f)).
table(up_v_mind_maxp_f,3,6,3,up(f)).
table(low_v_f_mind_maxp,3,6,3,low(maxp)).
table(up_v_f_mind_maxp,3,6,3,up(maxp)).
table(low_v_f_mind_minp,3,6,3,low(minp)).
table(up_v_f_mind_minp,3,6,3,up(minp)).
table(low_v_f_mind_maxd,3,6,3,low(maxd)).
table(up_v_f_mind_maxd,3,6,3,up(maxd)).
table(low_v_f_maxd_maxp,3,6,3,low(maxp)).
table(up_v_f_maxd_maxp,3,6,3,up(maxp)).
table(low_v_f_maxd_mind,3,6,3,low(mind)).
table(up_v_f_maxd_mind,3,6,3,up(mind)).
table(low_v_f_maxd_minp,3,6,3,low(minp)).
table(up_v_f_maxd_minp,3,6,3,up(minp)).
table(low_v_f_minp_maxd,3,6,3,low(maxd)).
table(up_v_f_minp_maxd,3,6,3,up(maxd)).
table(low_v_f_minp_mind,3,6,3,low(mind)).
table(up_v_f_minp_mind,3,6,3,up(mind)).
